### ISSUE TITLE
Pull GFSv16.3.5[6] GSI updates into develop

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#1322]
**Description**

Several small updates to the GSI have occurred in operations recently:

1. GFSv16.3.5 - allow continued use of atmospheric motion vectors from the GOES-W satellite as GOES-18 replaces GOES-17 and to include the assimilation of VIIRS radiances from S-NPP and NOAA-20 (which were to be included in the v16.3 implementation but were omitted due to data availability issues). See release notes: https://github.com/NOAA-EMC/global-workflow/blob/dev/gfs.v16/docs/Release_Notes.gfs.v16.3.5.md
2. GFSv16.3.6 - remove GMI from operational processing in the GSI. See release notes: https://github.com/NOAA-EMC/global-workflow/blob/dev/gfs.v16/docs/Release_Notes.gfs.v16.3.6.md

Make workflow-side changes related to this operational upgrades and update GSI hash when GSI-side work is completed. 

- [x] remove `crtm_ver` hack in `build_gsi_enkf.sh` introduced in PR #1319
- [x] remove line in `scripts/exglobal_atmos_analysis.sh` (done at NOAA-EMC/GSI hash [8c3609](https://github.com/NOAA-EMC/GSI/commit/8c360974de29d5e3d1f87d46b8fecb14c4972170).) Will resolve issue #1321.
- [x] disable GMI in `scripts/exglobal_atmos_analysis.sh` (done at https://github.com/NOAA-EMC/GSI/commit/e268acf909e7ea0daaa88b93299168bd654eed99):
```
#GMI1CRBF=${GMI1CRBF:-${COMIN_OBS}/${OPREFIX}gmi1cr.tm00.bufr_d${OSUFFIX}} # GMI temporarily disabled due to array overflow.
#$NLN $GMI1CRBF         gmibufr   # GMI temporarily disabled due to array overflow.
```
- [x] update GSI hash once (https://github.com/NOAA-EMC/GSI/issues/518 & https://github.com/NOAA-EMC/GSI/issues/520 complete) - new hash is [31b8b29](https://github.com/NOAA-EMC/GSI/commit/31b8b29a098fd8df50a9f0b11c6912d47ae0628c).

**Dependencies**

- [x] https://github.com/NOAA-EMC/GSI/issues/518
- [x] https://github.com/NOAA-EMC/GSI/issues/520

**Comment by KateFriedman-NOAA** [comment]
GSI issues are completed. @RussTreadon-NOAA confirmed "NOAA-EMC/GSI develop has been updated to crtm/2.4.0.  The hash to grab is [31b8b29](https://github.com/NOAA-EMC/GSI/commit/31b8b29a098fd8df50a9f0b11c6912d47ae0628c)."

**Comment by KateFriedman-NOAA** [comment]
Create fork branch for this work: https://github.com/KateFriedman-NOAA/global-workflow/tree/feature/new_gsi_hash_31b8b29

**Comment by KateFriedman-NOAA** [comment]
Running C96C48L127 ATM-only cycled test on Hera with `feature/new_gsi_hash_31b8b29` branch.

**Comment by KateFriedman-NOAA** [comment]
Test ran over the weekend and completed 5.5 cycles without issue on Hera. Already tested the changes in this issue in various tests on WCOSS2 and these changes are running in GFSv16 operations.
