### ISSUE TITLE
GFSv16.3.7 - Meteosat Full Earth Scan Outage and Satellite Swap

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#1368]
**Description**

Email received from @ADCollard 3/3:
```
Last week, EUMETSAT announced that they will be switching Meteosat-10 for Meteosat-11 as the satellite performing 
full-Earth scans at 0degrees longitude on March 21 2023.   For us this means that we need to switch on the processing
of Meteosat-10 winds in the GFS system to ensure continuity of data in the DA system.  As we will only receive one
data source at a time, we can make this change at any time before the switch and the data switch would then happen
automatically.

We are putting the final touches to a GSI tag to implement this change.
```

**Workflow Changes**

- [x] New GSI tag: `Externals.cfg` and `sorc/checkout.sh`
- [x] New release notes [under docs folder](https://github.com/NOAA-EMC/global-workflow/tree/release/gfs.v16.3.7/docs)
- [x] Update version number in [versions/run.ver](https://github.com/NOAA-EMC/global-workflow/blob/release/gfs.v16.3.7/versions/run.ver#L1:L2) to `v16.3.7`

**Tasks**
- [x] Create release branch: [release/gfs.v16.3.7](https://github.com/NOAA-EMC/global-workflow/tree/release/gfs.v16.3.7)
- [x] Make workflow changes for upgrade in release branch (add additional checklist items as needed) (PR #1369)
- [x] Create release notes @ADCollard (PR #1369)
- [x] Cut hand-off tag for CDF ([EMC-v16.3.7](https://github.com/NOAA-EMC/global-workflow/releases/tag/EMC-v16.3.7))
- [x] Submit CDF to NCO @ADCollard 
- [x] Implementation into operations complete (done during 2023032112 cycle)
- [x] Merge release branch into operational branch (PR #1407)
- [x] Cut version tag from operational branch (`gfs.v16.3.7`)
- [x] Release new version tag (https://github.com/NOAA-EMC/global-workflow/releases/tag/gfs.v16.3.7)
- [x] Announce to users
- [x] Update Read-The-Docs operations status version in develop (https://github.com/NOAA-EMC/global-workflow/pull/1417)

**Comment by RussTreadon-NOAA** [comment]
GSI tag [gfsda.v16.3.7](https://github.com/NOAA-EMC/GSI/releases/tag/gfsda.v16.3.7) has been created and is ready for inclusion in g-w [release/gfs.v16.3.7](https://github.com/NOAA-EMC/global-workflow/tree/release/gfs.v16.3.7).

**Comment by KateFriedman-NOAA** [comment]
@ADCollard @RussTreadon-NOAA I have cut the EMC-v16.3.7 hand-off tag for the CDF from the `release/gfs.v16.3.7` branch: https://github.com/NOAA-EMC/global-workflow/releases/tag/EMC-v16.3.7

**Comment by ADCollard** [comment]
Thanks @KateFriedman-NOAA @RussTreadon-NOAA The CDF has been submitted.

**Comment by KateFriedman-NOAA** [comment]
Unless we hear otherwise, an ARFC is being submitted to implement this update tomorrow 3/21 @ 12z.

**Comment by KateFriedman-NOAA** [comment]
Update: implementing tomorrow @ 11z for 06z GDAS.

**Comment by KateFriedman-NOAA** [comment]
Implemented during 12z gfs today. Slightly delayed due to Enhanced Caution.

**Comment by KateFriedman-NOAA** [comment]
From March 22nd SDM log:

```
4e. 1212Z - SPA TL Steven Earle relayed the following ARFC on
behalf of IDSB Chief Carissa Klemmer: "Update the GFS to change
to start processing Meteosat-10 data, in support of an incoming
dataset change by EUMETSAT."  Approved by NCO Director Ben
Kyger, NCO Security, and the SDM.  1430Z - SPA Simon Hsiao began
this work, approved to proceed in ECE...1900Z - Completed.
(RLR/KAK)
```

**Comment by KateFriedman-NOAA** [comment]
Cut `gfsv16.3.7` tag from `dev/gfs.v16` branch and released: https://github.com/NOAA-EMC/global-workflow/releases/tag/gfs.v16.3.7

**Comment by KateFriedman-NOAA** [comment]
From March 24th RFC memo:

```
RFC 10762 - On WCOSS2, updated the GFS to v16.3.7 to handle the
Meteosat-11 data outage and satellite swap that occurred on March 21 at 0800Z.
This GFS v16.3.7 update turned on Meteosat-10 Atmospheric Motion Vectors
(AMVs) in operational processing in the GSI. Implemented on March 21 at
1430Z.
```
