### ISSUE TITLE
Marine DA updates

### ISSUE THREAD

**Issue by guillaumevernieres** [NOAA-EMC/global-workflow#1480]
### Description
We (@AndrewEichmann-NOAA and @guillaumevernieres ) have an [Epic open in the GDASApp](https://github.com/noaa-emc/gdasapp/issues/416) repository which details the updates that we will be submitting as PR's in the next few days, possibly starting 04/19/2023. None of these updates include any refactoring of the j-jobs/scripts following what @CoryMartin-NOAA and @RussTreadon-NOAA did.
The goal of this issue/Epic is to simply merge what allowed us to cycle a WCDA system and produce reasonable results over the past few weeks. The refactoring of the j-jobs/scripts will be the subject of the next Epic/Sprint.

### Bug-fixes or feature added
- [x] Move the work done in the POST j-job into a dedicated ex-script (https://github.com/noaa-emc/gdasapp/issues/439). @AndrewEichmann-NOAA 
- [x] Add the verify j-job as part of the cycling (https://github.com/noaa-emc/gdasapp/issues/421). @AndrewEichmann-NOAA 
- [x] Bug in the archiving j-job (https://github.com/noaa-emc/gdasapp/issues/417). @AndrewEichmann-NOAA 
- [x] New separate j-job to post process increments and analysis for IAU or direct insertion (https://github.com/noaa-emc/gdasapp/issues/418). @guillaumevernieres 
- [x] ... I'm pretty sure I forgot something

All of the changes above only touches 14 files, so we might submit most of the work in ~2 PR's if it's OK with @aerorahul , @WalterKolczynski-NOAA and other code managers.

**Comment by WalterKolczynski-NOAA** [comment]
@guillaumevernieres is this issue still current or should we open more focused issues? Thanks.

**Comment by guillaumevernieres** [comment]
> @guillaumevernieres is this issue still current or should we open more focused issues? Thanks.

Sorry @WalterKolczynski-NOAA , we forgot to close this issue.
