### ISSUE TITLE
Update GSI fix files in global-workflow

### ISSUE THREAD

**Issue by emilyhcliu** [NOAA-EMC/global-workflow#1550]
**Description**

While checking the global-workflow run on HERA from feature/gdas_init_com_reorg, it was found that the fix files associated with GSI were not up-to-date with the GSI develop.  These fix files are associated with the pre-operational version located on HERA at:
/scratch1/NCEPDEV/global/glopara/fix/gsi/20221128

**Tasks**

- [x] Discuss needs with global-workflow developer assigned to request.
- [x] Add/update/remove fix file(s) in fix sets on supported platforms (global-workflow assignee task).
- [x] Update "Fix File Management" spreadsheet (https://docs.google.com/spreadsheets/d/1BeIvcz6TO3If4YCqkUK-oz_kGS9q2wTjwLS-BBemSEY/edit?usp=sharing).

**Comment by KateFriedman-NOAA** [comment]
Related comment from issue #1494:

> Here is the fix directory version in current GSI develop repository:
https://github.com/NOAA-EMC/GSI-fix/tree/0be26971f834fe9b1d5b118e1e0ffed53facf671
Shall we update the fix to the one in GSI develop?

Most likely but you and @CatherineThomas-NOAA have most of the say in this. Are there a bunch of differences in this version compared to the current `20221128` set we have? I'm thinking we pull this version into a new `20230112` folder in the fix set to match the date on this hash. And then [update](https://github.com/NOAA-EMC/global-workflow/blob/develop/versions/fix.ver#L16) `gsi_ver` in `versions/fix.ver` to be the new `20230112` set. Thoughts? 

Tagging @aerorahul and @WalterKolczynski-NOAA for inputs.

**Comment by emilyhcliu** [comment]
> Related comment from issue #1494:
> 
> > Here is the fix directory version in current GSI develop repository:
> > https://github.com/NOAA-EMC/GSI-fix/tree/0be26971f834fe9b1d5b118e1e0ffed53facf671
> > Shall we update the fix to the one in GSI develop?
> 
> Most likely but you and @CatherineThomas-NOAA have most of the say in this. Are there a bunch of differences in this version compared to the current `20221128` set we have? I'm thinking we pull this version into a new `20230112` folder in the fix set to match the date on this hash. And then [update](https://github.com/NOAA-EMC/global-workflow/blob/develop/versions/fix.ver#L16) `gsi_ver` in `versions/fix.ver` to be the new `20230112` set. Thoughts?
> 
> Tagging @aerorahul and @WalterKolczynski-NOAA for inputs.

@KateFriedman-NOAA The files in  `20221128`  are pre-operational.  They need to be updated.  The v16.3 fix files have been merged into the GSI-fix repository.  Since `20221128` needs to be updated, let's update them to the latest.

**Comment by KateFriedman-NOAA** [comment]
@emilyhcliu So you'd prefer the `20221128` set be overwritten with the latest set? I just need confirmation on that to proceed. I'm either 1) overwriting the `20221128` set with the latest set or 2) creating an updated set (`20230112`) to preserve the prior set. Please confirm your preference for clarification and I'll proceed. Wanna make sure I have the correct understanding before potentially overwriting the current set. Thanks! :)

**Comment by emilyhcliu** [comment]
> @emilyhcliu So you'd prefer the `20221128` set be overwritten with the latest set? I just need confirmation on that to proceed. I'm either 1) overwriting the `20221128` set with the latest set or 2) creating an updated set (`20230112`) to preserve the prior set. Please confirm your preference for clarification and I'll proceed. Wanna make sure I have the correct understanding before potentially overwriting the current set. Thanks! :)

I  like your option-2 (create an updated set (`20230112`).  
The last update in the GSI-fix repository is 20230112.  I checked the global_convinfo.txt.  The latest changes from gfs.v16.3.4 and gfs.v16.3.5 updates are also included.

**Comment by RussTreadon-NOAA** [comment]
Which binary GSI fix files in the EIB maintained `fix/gsi/20221128` need to be removed, updated, or added?

**Comment by KateFriedman-NOAA** [comment]
I cloned the latest hash of `GSI-fix` repo into a new `20230112` folder in the Hera fix set (in case we go that route) and did a simple recursive diff. Here is the output:

```
[role.glopara@hfe03 fix]$ cd gsi/
[role.glopara@hfe03 gsi]$ ll
total 24
drwxr-sr-x 4 role.glopara global 24576 Jan  9 14:38 20221128
[role.glopara@hfe03 gsi]$ git clone https://github.com/NOAA-EMC/GSI-fix.git ./20230112
Cloning into './20230112'...
remote: Enumerating objects: 796, done.
remote: Counting objects: 100% (796/796), done.
remote: Compressing objects: 100% (373/373), done.
remote: Total 796 (delta 439), reused 773 (delta 423), pack-reused 0
Receiving objects: 100% (796/796), 8.54 MiB | 20.67 MiB/s, done.
Resolving deltas: 100% (439/439), done.
Checking out files: 100% (296/296), done.
[role.glopara@hfe03 gsi]$ ll
total 44
drwxr-sr-x 4 role.glopara global 24576 Jan  9 14:38 20221128
drwxr-sr-x 4 role.glopara global 20480 May  1 15:06 20230112
[role.glopara@hfe03 gsi]$ diff -r 20221128 20230112 
Only in 20230112: .git
Only in 20230112: .gitignore
Only in 20221128: 200urma2p5_howv_lng_lat.bin
Only in 20221128: 330urma2p5_howv_lng_lat.bin
Only in 20221128: 500urma2p5_howv_lng_lat.bin
Only in 20221128: Big_Endian
Only in 20230112: CMakeLists.txt
Only in 20230112: LICENSE.md
Only in 20230112: README.md
Only in 20221128: Rcov_crisn20
Only in 20221128: Rcov_crisnpp
Only in 20221128: Rcov_iasialand
Only in 20221128: Rcov_iasiasea
Only in 20221128: Rcov_iasibland
Only in 20221128: Rcov_iasibsea
Only in 20221128: Rcov_iasicland
Only in 20221128: Rcov_iasicsea
Only in 20221128: VLabRepoQuickTips.txt
Only in 20221128: berror_stats_withsiglats
Only in 20221128: global_CRTM_AerosolCoeff.f77
Only in 20221128: global_CRTM_CldCoeff.f77
Only in 20221128: global_CRTM_EmisCoeff.f77
Only in 20221128: global_CRTM_SpcCoeff.f77
Only in 20221128: global_CRTM_TauCoeff.f77
diff -r 20221128/global_anavinfo.l127.txt 20230112/global_anavinfo.l127.txt
22d21
<   cw      127      10         cloud_condensate     cw
24a24,27
>   qr      127      12         rain                 qr
>   qs      127      12         snow                 qs
>   qg      127      12         graupel              qg
> ! cf      127       1         cloud amount         cf
35c38
<  cw   127    met_guess
---
> !cw   127    met_guess
45c48
<  cw   127     met_guess
---
> !cw   127     met_guess
59a63,65
>  qr      127      1     met_guess    qr
>  qs      127      1     met_guess    qs
>  qg      127      1     met_guess    qg
101c107,111
<  cw      127      1       1.00        -1.0     state    cw
---
>  ql      127      1       1.00        -1.0     state    ql
>  qi      127      1       1.00        -1.0     state    qi
>  qr      127      1       1.00        -1.0     state    qr
>  qs      127      1       1.00        -1.0     state    qs
>  qg      127      1       1.00        -1.0     state    qg
Only in 20230112: global_anavinfo_qlqi.l127.txt
diff -r 20221128/global_convinfo.txt 20230112/global_convinfo.txt
139,140c139,140
<  uv       245  271    1     3.0      0      0      0   1.3  20.0   1.4   1.3  0.005000     0  200.   100.      0    0.     0.   15   -8
<  uv       245  272   -1     3.0      0      0      0   1.3  20.0   1.4   1.3  0.005000     0  200.   100.      0    0.     0.   15   -8
---
>  uv       245  271   -1     3.0      0      0      0   1.3  20.0   1.4   1.3  0.005000     0  200.   100.      0    0.     0.   15   -8
>  uv       245  272    1     3.0      0      0      0   1.3  20.0   1.4   1.3  0.005000     0  200.   100.      0    0.     0.   15   -8
145,146c145,146
<  uv       246  271    1     3.0      0      0      0   1.3  20.0   1.4   1.3  0.005000     0  200.   100.      0    0.     0.   15   -8
<  uv       246  272   -1     3.0      0      0      0   1.3  20.0   1.4   1.3  0.005000     0  200.   100.      0    0.     0.   15   -8
---
>  uv       246  271   -1     3.0      0      0      0   1.3  20.0   1.4   1.3  0.005000     0  200.   100.      0    0.     0.   15   -8
>  uv       246  272    1     3.0      0      0      0   1.3  20.0   1.4   1.3  0.005000     0  200.   100.      0    0.     0.   15   -8
151,152c151,152
<  uv       247  271    1     3.0      0      0      0   2.5  20.0   1.4   2.5  0.005000     0    0.     0.      0    0.     0.   15   -8
<  uv       247  272   -1     3.0      0      0      0   2.5  20.0   1.4   2.5  0.005000     0    0.     0.      0    0.     0.   15   -8
---
>  uv       247  271   -1     3.0      0      0      0   2.5  20.0   1.4   2.5  0.005000     0    0.     0.      0    0.     0.   15   -8
>  uv       247  272    1     3.0      0      0      0   2.5  20.0   1.4   2.5  0.005000     0    0.     0.      0    0.     0.   15   -8
Only in 20230112: gsi_binary_files.cmake
Only in 20221128: nam_CRTM_SpcCoeff.f77
Only in 20221128: nam_CRTM_TauCoeff.f77
Only in 20221128: nam_glb_berror.f77
Only in 20221128: nam_glb_berror.f77.gcv
Only in 20221128: nam_nmm_berror.f77
Only in 20221128: nam_nmm_berror.f77.gcv
Only in 20221128: nam_nmmstat_na
Only in 20221128: nam_nmmstat_na_glberror.gcv
Only in 20221128: rap_berror_stats_global
Only in 20221128: rrfs_glb_berror.l127y770.f77
Only in 20221128: rtma_nmm_berror.f77
Only in 20221128: rtma_random_flips
Only in 20221128: urma2p5.maxT.grb1_0
Only in 20221128: urma2p5.maxT.grb2_0
Only in 20221128: urma2p5.minT.grb1_0
Only in 20221128: urma2p5.minT.grb2_0
Only in 20221128: urma2p5_errfield.dat_clim
Only in 20221128: urma2p5_errfield_with_mitm.dat_clim
Only in 20221128: urma2p5_errfield_with_mxtm.dat_clim
Only in 20221128: urma2p5_fltnorm.dat_chi
Only in 20221128: urma2p5_fltnorm.dat_cldch
Only in 20221128: urma2p5_fltnorm.dat_gust
Only in 20221128: urma2p5_fltnorm.dat_howv
Only in 20221128: urma2p5_fltnorm.dat_mitm
Only in 20221128: urma2p5_fltnorm.dat_mxtm
Only in 20221128: urma2p5_fltnorm.dat_ps
Only in 20221128: urma2p5_fltnorm.dat_pseudorh
Only in 20221128: urma2p5_fltnorm.dat_psi
Only in 20221128: urma2p5_fltnorm.dat_t
Only in 20221128: urma2p5_fltnorm.dat_tcamt
Only in 20221128: urma2p5_fltnorm.dat_vis
Only in 20221128: urma2p5_fltnorm.dat_wspd10m
Only in 20221128: urma2p5_howv_lng_lat.bin
Only in 20221128: urma2p5_howv_var_lat.bin
Only in 20221128: urma2p5_latlon_mpfactor.dat
Only in 20221128: urma2p5_random_flips
Only in 20221128: urma2p5_rd2.out_hrrr_on_cohreswexp
Only in 20221128: urma2p5_rd2.out_hrrr_on_cohreswexp_standby_mode_uses_lastest_HRRR_composed_1Nov2016
Only in 20221128: urma2p5_rd2.out_namnest_wexp_on_cohreswexp
Only in 20221128: urma2p5_rd2.out_namnest_wexp_on_cohreswexp_standby_mode_uses_new_NAM_composed_1Nov2016
Only in 20221128: urma2p5_regional_berror.f77
Only in 20221128: urma2p5_slmask.dat_nolakes
Only in 20221128: urma2p5_terrain.dat
Only in 20221128: vqctp001.dat
`

**Comment by KateFriedman-NOAA** [comment]
I notice that the newer set is much smaller than the prior set...is that expected? Did I do the clone correctly?

```
[role.glopara@hfe03 gsi]$ pwd
/scratch1/NCEPDEV/global/glopara/fix/gsi
[role.glopara@hfe03 gsi]$ du -h --summarize *
2.3G    20221128
100M    20230112
```

**Comment by aerorahul** [comment]
@KateFriedman-NOAA 
The GSI fix data is now split into "binary" files on FTP and ascii files on Github.
We need to clone the ascii fix files from Github and copy the binary files from FTP. 
I can help.

**Comment by KateFriedman-NOAA** [comment]
> @KateFriedman-NOAA The GSI fix data is now split into "binary" files on FTP and ascii files on Github. We need to clone the ascii fix files from Github and copy the binary files from FTP. I can help.

@aerorahul Ah, gotcha, thanks for that reminder and offer of help! I'll make sure to document this in the fix file spreadsheet for future reference.

**Comment by aerorahul** [comment]
I will add a `INSTALL.md` in the `GSI-fix` repository with instructions on how to populate the `fix/gsi` directory for the purposes of shared installation.

**Comment by KateFriedman-NOAA** [comment]
Alrighty, @aerorahul helped me get a proper install of the updated `gsi-fix` on Hera (now rsync'd to the other platforms too). The size looks good. See here on Hera: `/scratch1/NCEPDEV/global/glopara/fix/gsi/20230112`

```
[role.glopara@hfe02 gsi]$ pwd
/scratch1/NCEPDEV/global/glopara/fix/gsi
[role.glopara@hfe02 gsi]$ du -h --summarize *
2.3G    20221128
2.3G    20230112
```

@emilyhcliu Please confirm if we're good to go with this new set. I also updated `gsi_ver` in `fix.ver` in the branch in https://github.com/NOAA-EMC/global-workflow/pull/1535 @ [d57feb1](https://github.com/NOAA-EMC/global-workflow/pull/1535/commits/d57feb1edd30ef456b16799374a5bdc44bf77be0) to use this updated set. If this set is good I will proceed with merging that PR. Thanks!

**Comment by KateFriedman-NOAA** [comment]
@emilyhcliu We good to proceed with this updated GSI fix set and merging #1535? Would be great to complete this today. Thanks!

**Comment by KateFriedman-NOAA** [comment]
Unless there are any objections I will consider this updated GSI fix set good-to-go and merge PR #1535 this afternoon. Thanks all!

**Comment by RussTreadon-NOAA** [comment]
**Observation, not objection**

GSI and EnKF source code reside in [NOAA-EMC/GSI](https://github.com/NOAA-EMC/GSI).  A recursive clone of this repository populates the local `fix` with ASCII GSI-fix files from [NOAA-EMC/GSI-fix](https://github.com/NOAA-EMC/GSI-fix) at a particular hash.   Execution of `ush/build.sh` populates the local `fix` with binary GSI-fix files from a EIB staged location.   Variable `GSI_BINARY_SOURCE_DIR` in the machine specific GSI modulefile provides the path to the EIB staged GSI binary files.

DA developers often work in local clones of the authoritative NOAA-EMC/GSI or forked copies of the central repository.  If a developer modifies fix file(s), where the change(s) should be captured (version control or otherwise managed) depends on the nature of their work.   

- If the work is for an operational GFS v16.x implementation, ASCII and binary GSI fix files are maintained in gerrit:GSI-fix.  
- If the work is for GFS v17, ASCII files are maintained in NOAA-EMC/GSI-fix.  Binary GSI fix files are hosted in EIB maintained directories.
- If the work is for regional GSI applications, it seems ASCII GSI fix files should be captured in NOAA-EMC/GSI-fix.  While EIB hosts binary GSI fix files in staged locations, I don't think this was done with the intention of supporting regional GSI DA.   Perhaps regional DA groups maintain their own binary GSI repositories or use other means.

Diligence is necessary to ensure we properly version control or otherwise track the evolution of ASCII and binary GSI fix files.

**Comment by aerorahul** [comment]
Thank you for capturing the state of the GSI-fix files and their maintenance.
While EIB maintains a copy of the fix files (binary + ascii) in the central place, EIB will not update this space without approval from the GSI-fix POC (@RussTreadon-NOAA).
If the DA developers wish update the fix file, they will make the request via global-workflow "Fix file update template".  This will effect an update in the global-workflow hash with the fix file update.

**Comment by emilyhcliu** [comment]
> * EMC/GSI-fix.  Binary GSI fix files are hosted in EIB maintained

@KateFriedman-NOAA I am sorry that I missed your message.  I am behind digesting the e-mails coming to me.   I saw that you checked out the GSI-fix repo (the latest one detached at 0be2697).  This is correct!  These are the ascii part of the fix files.  The binary part are download through FTP while running the build.sh.  Rahul helped.  So, I think the binary part of the update should be good.  

I checked the ascii files in /scratch1/NCEPDEV/global/glopara/fix/gsi/20230112.

They look right to me.

**Comment by KateFriedman-NOAA** [comment]
Thanks for confirming @emilyhcliu ! This task should now be complete and the remaining GFSv16.3 GSI updates in `develop`.

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA @emilyhcliu I notice that the GSI modulefiles contain a path to fix files...Hera example:

https://github.com/NOAA-EMC/GSI/blob/develop/modulefiles/gsi_hera.intel.lua#L29
```
pushenv("GSI_BINARY_SOURCE_DIR", "/scratch1/NCEPDEV/global/glopara/fix/gsi/20221128")
```

This is now out of date with the recent change to use the `20230112` set.

Should these `GSI_BINARY_SOURCE_DIR` lines have also been updated with the PR for this issue and a new GSI hash used? 

Also, perhaps better, can these lines be updated to accept `gsi_ver` from the workflow `fix.ver`?

**Comment by RussTreadon-NOAA** [comment]
NOAA-EMC/GSI fix populates a local `fix` directory with binary GSI fix files by one of two mechanisms during the GSI build process
1. copy GSI binary files from EIB directory `GSI_BINARY_SOURCE_DIR`
2. if `GSI_BINARY_SOURCE_DIR` does not exist, download binary tarball from [ftp.emc.ncep.noaa.gov/static_files/public/gsi](https://ftp.emc.ncep.noaa.gov/static_files/public/gsi)

While this issue documents creations of a new `GSI_BINARY_SOURCE_DIR`, a corresponding new binary tarball was not created and pushed `ftp.emc.ncep.noaa.gov`.    

GSI issue [#580](https://github.com/NOAA-EMC/GSI/issues/580) has been created to document the updating of `GSI_BINARY_SOURCE_DIR` in GSI modulefiles.   We should also update the `SHA` of the binary tarball which NOAA-EMC/GSI points at.  This can not be done until a new binary GSI tarball is created and pushed to `ftp.emc.ncep.noaa.gov`.

Do you want this need captured in a new issue or simply reopen this issue?

**Comment by KateFriedman-NOAA** [comment]
> Do you want this need captured in a new issue or simply reopen this issue?

New issue please. Thanks!

**Comment by RussTreadon-NOAA** [comment]
I downloaded `gsi-fix-b90f7b.tgz` from [ftp.emc.ncep.noaa.gov/static_files/public/gsi](https://ftp.emc.ncep.noaa.gov/static_files/public/gsi).   After a gunzip and tar -xvf, comparison of the contents of the tarball show now differences with like files in `/scratch1/NCEPDEV/global/glopara/fix/gsi/20230112/`.    

A review of this issue shows that only ASCII GSI fix files were updated in 20230112.   This is consistent with comparison of the tarball contents with 20230112.   As such, we can keep using the binary GSI tarball `gsi-fix-b90f7b.tgz` posted at  [ftp.emc.ncep.noaa.gov/static_files/public/gsi](https://ftp.emc.ncep.noaa.gov/static_files/public/gsi).  No new issue will be opened.

It's challenging to keep everything aligned when hosting GSI fix files in various locations with a variety of approaches as [noted above](https://github.com/NOAA-EMC/global-workflow/issues/1550#issuecomment-1539003531).
