### ISSUE TITLE
Remove gdas/bump fix files

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#1552]
**Description**

Remove the gdas bump fix files from the primary development fix file set (`$FIX_DIR/gdas/bump/20220805`)

**Tasks**

- [x] Discuss needs with global-workflow developer assigned to request.
- [x] Remove bump fix file(s) in fix sets on supported platforms (global-workflow assignee task).
- [x] Update "Fix File Management" spreadsheet (https://docs.google.com/spreadsheets/d/1BeIvcz6TO3If4YCqkUK-oz_kGS9q2wTjwLS-BBemSEY/edit?usp=sharing).
- [x] Remove `bump_ver` from `versions/fix.ver` (https://github.com/NOAA-EMC/global-workflow/blob/develop/versions/fix.ver#L10) (Done @ [a1d93de](https://github.com/KateFriedman-NOAA/global-workflow/commit/a1d93debfa1b7c3aa7c51c9d1b9ff5cb1b18cc9c)).
- [x] Remove "bump" from `sorc/link_workflow.sh` fix linking. (Done @ [1a2ad5f](https://github.com/KateFriedman-NOAA/global-workflow/commit/1a2ad5fe65a2ea3e167d2b85cc066243ae3d6eb9)).
- [ ] Update IC folder name and tree in RTD (https://github.com/NOAA-EMC/global-workflow/pull/1562).

FYI @RussTreadon-NOAA

**Comment by KateFriedman-NOAA** [comment]
@RussTreadon-NOAA @aerorahul Do you know if any of these "bump" references in global-workflow need removal or adjustment as well?

```
parm/config/config.aeroanl:export BERROR_DATA_DIR=${FV3JEDI_FIX}/bump/aero/${CASE_ANL}/
ush/python/pygfs/task/atm_analysis.py:        This method will construct a dictionary of either bump of gsibec background
ush/python/pygfs/task/atm_analysis.py:                                       'bump': self._get_berror_dict_bump,
ush/python/pygfs/task/atm_analysis.py:    def _get_berror_dict_bump(config: Dict[str, Any]) -> Dict[str, List[str]]:
ush/python/pygfs/task/atm_analysis.py:        """Compile a dictionary of atm bump background error files to copy
ush/python/pygfs/task/atm_analysis.py:        This method will construct a dictionary of atm bump background error
ush/python/pygfs/task/atm_analysis.py:            a dictionary of atm bump background error files to copy for FileHandler
ush/python/pygfs/task/aero_analysis.py:        if self.task_config.get('STATICB_TYPE', 'identity') in ['bump']:
```

**Comment by aerorahul** [comment]
no.  these should stay.

**Comment by RussTreadon-NOAA** [comment]
I would not alter any of the bump references in g-w.   Do you have a g-w email list to which you can post your question?

**Comment by KateFriedman-NOAA** [comment]
I will leave those bump references alone, thanks for the feedback! Can reevaluate in the future if needed. I will only remove the `bump_ver` from `versions/fix.ver` and "bump" from the `gdas_sub` list in `sorc/link_workflow.sh` in global-workflow...in addition to removing the files themselves from the fix sets. See the task list in the main issue comment above.

**Comment by KateFriedman-NOAA** [comment]
Proceeding with the deletion of the `gdas/bump` files from the fix sets on Hera, Orion, WCOSS2s, and Jet.

**Comment by KateFriedman-NOAA** [comment]
The `gdas/bump` folder has now been removed from the fix sets on Hera, Orion, WCOSS2s, and Jet.

The size of the `gdas` fix subfolder before removal of the `gdas/bump` folder:

```
[role.glopara@hfe03 gdas]$ pwd
/scratch1/NCEPDEV/global/glopara/fix
[role.glopara@hfe03 fix]$ du -h --summarize gdas  
374G    gdas
[role.glopara@hfe03 fix]$ du -h --summarize gdas/*
373G    gdas/bump
1.6G    gdas/crtm
268K    gdas/fv3jedi
241M    gdas/gsibec
```

....and after removal of the `gdas/bump` folder:

```
[role.glopara@hfe03 fix]$ cd gdas/
[role.glopara@hfe03 gdas]$ ll
total 16
drwxr-sr-x 3 role.glopara global 4096 Aug  4  2022 bump
drwxr-sr-x 3 role.glopara global 4096 Aug  4  2022 crtm
drwxr-sr-x 3 role.glopara global 4096 Aug  4  2022 fv3jedi
drwxr-sr-x 3 role.glopara global 4096 Oct 31 13:59 gsibec
[role.glopara@hfe03 gdas]$ rm -rf bump
[role.glopara@hfe03 gdas]$ ll
total 12
drwxr-sr-x 3 role.glopara global 4096 Aug  4  2022 crtm
drwxr-sr-x 3 role.glopara global 4096 Aug  4  2022 fv3jedi
drwxr-sr-x 3 role.glopara global 4096 Oct 31 13:59 gsibec
[role.glopara@hfe03 gdas]$ cd ../
[role.glopara@hfe03 fix]$ du -h --summarize gdas
1.8G    gdas
[role.glopara@hfe03 fix]$ du -h --summarize gdas/*
1.6G    gdas/crtm
268K    gdas/fv3jedi
241M    gdas/gsibec
```

**Comment by KateFriedman-NOAA** [comment]
Reopening to updated documentation and then close when done.

**Comment by KateFriedman-NOAA** [comment]
Crossed wires. Wrong issue. Closing.
