### ISSUE TITLE
Port to Hercules

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#1588]
**Description**

Update the system to support the new MSU Hercules.

**Dependencies**

- [x] EPIC hpc-stack/spack-stack available
- [x] Staged fix files in place (if not accessible from Orion side) - update `link_workflow.sh` to add Hercules on Orion line
- [x] Staged ICs in place (if not accessible from Orion side) - update `config.coupled_ic` for Hercules (same as Orion)
- [x] Test GDA in place (if not accessible from Orion side) - add Orion `DMPDIR` to Hercules hosts file
- [x] Workflow updates (e.g. env)
- [x] ufs-weather-model support: https://github.com/ufs-community/ufs-weather-model/pull/1733
- [x] UPP support https://github.com/NOAA-EMC/UPP/pull/760
- [x] UFS_UTILS support https://github.com/ufs-community/UFS_UTILS/pull/880
- [x] gfs-utils support
- [x] GSI-EnKF support https://github.com/NOAA-EMC/GSI/issues/574
- [x] GSI-Utils support
- [ ] GSI-Monitor support
- [ ] GDASApp support https://github.com/NOAA-EMC/GDASApp/pull/774
- [ ] EMC_verif-global support
- [x] OBSPROC packages support (obsproc/prepobs) https://github.com/NOAA-EMC/prepobs/issues/21
- [x] TC_tracker support https://github.com/NOAA-EMC/TC_tracker/issues/3
- [x] Fit2Obs support ~https://github.com/NOAA-EMC/Fit2Obs/issues/15~ Not necessary to port.  The Orion executables work fine on Hercules.

spack-stack is available on hercules via:
```sh
module purge
module use /work/noaa/epic-ps/role-epic-ps/spack-stack/modulefiles
```

Information from admin announcement:

A new computing resource is now available for the NOAA R&D HPC user community at Mississippi State University (MSU).
The new system has been named “Hercules” and as with Orion, is owned and managed by MSU. As this is a brand new
system, with a brand new software stack, we would like your help in flushing out any issues before we place the system
into full production. So we are asking our current Orion users to assist us with the pre-operational testing of this new
system. We would greatly appreciate it if you could try compiling your models, running your models, testing your
workflows, and then provide us with feedback by emailing “rdhpcs.orion.help@noaa.gov”. Please also email any questions
or issues to the same email address.  If everything goes well with the testing then we hope to announce full production
in early May. Thank you for all your help!

Hercules System Overview:

Manufacturer: Dell EMC
Model: PowerEdge C6520
Interconnect: Mellanox Infiniband NDR-200
Processor: Xeon Platinum 8380 40Core@2.3GHz
Total System Memory: 262,144 GB
Total Compute Nodes: 512
Cores per Node: 80
Total Cores: 40,960
File Systems: 2 DDN Lustre File system /work & /work2 (shared with Orion)
Allocations: Core-hour allocations (independent from Orion), Disk allocations (Shared between Orion and Hercules)
Home File System: NFS with 10GB of space per user
Other Node Types: Login nodes (4), Development nodes (2), and Data Transfer nodes (4)

MSU’s Official Hercules Documentation:

https://intranet.hpc.msstate.edu/helpdesk/resource-docs/hercules_guide.php

NOAA RDHPCS Supplemental Documentation

How to run jobs:

https://oriondocs.rdhpcs.noaa.gov/wiki/index.php/Running_Jobs_on_MSU-HPC

Please note the following:

During the pre-operational test phase we are only allowing “windfall” QOS jobs to run. This will allow you to run test jobs
without negatively impacting your project’s Fairshare. Once the system is ready for production then we will upload the
core-hour allocations and make all QOSs available for use.

Known Issues (supplemental):

https://oriondocs.rdhpcs.noaa.gov/wiki/index.php/Known_Issues

Differences between Orion and Hercules:

https://oriondocs.rdhpcs.noaa.gov/wiki/index.php/Frequently_Asked_Questions#What_are_the_differences_between_Orion_and_Hercules.3F

**Comment by DavidHuber-NOAA** [comment]
The gsi-monitor requires some Perl modules that are not currently installed on Hercules.  I will proceed for the time being by disabling the monitor jobs on the system then circle back when they are installed.  Anticipate that won't happen until next year due to MSU personnel on leave.

**Comment by DavidHuber-NOAA** [comment]
The `prepobs_prepdata` executable is crashing on Hercules due to the missing MKL library only available on Orion, though the gdasprep and gfsprep jobs are continuing to process thereafter.  This means prepobs and obsproc need to be ported to Hercules and that the Orion installations are not compatible.

That said, it seems like a bug that the failure of `prepobs_prepdata` does not stop the processing of the *prep jobs.  What do you think @KateFriedman-NOAA?  An example log is available here: `/work/noaa/global/dhuber/para/com/cycled_herc2/logs/2021110912/gdasprep.log`.

**Comment by KateFriedman-NOAA** [comment]
> That said, it seems like a bug that the failure of prepobs_prepdata does not stop the processing of the *prep jobs.

@DavidHuber-NOAA Definitely does seem to be a bug and may be another one in addition to what we've observed with obsproc (https://github.com/NOAA-EMC/global-workflow/issues/691). Would you mind saving that log and noting the failure in issue #691?

We have a branch in prepobs that we're currently using on the R&Ds post-COM-reorg: https://github.com/NOAA-EMC/prepobs/tree/feature/GFSv17_com_reorg

I'm guessing we'll need to install a copy of the updated prepobs branch (with Hercules support) on Hercules to use on Hercules or are we able to update the Orion install for use on Hercules?

Do you mind making Hercules updates for prepobs and sending them into that `feature/GFSv17_com_reorg` branch? I'm happy to review and merge a PR if you can submit one into it. As listed in the main comment for this issue, we have a prepobs issue open for Hercules changes if needed (https://github.com/NOAA-EMC/prepobs/issues/21). We don't have [an obsproc issue](https://github.com/NOAA-EMC/obsproc/issues) or branch for any ports or the COM-reorg (didn't need). Don't know if we will need one for Hercules since the codes we use are in prepobs.

**Comment by DavidHuber-NOAA** [comment]
> > That said, it seems like a bug that the failure of prepobs_prepdata does not stop the processing of the *prep jobs.
> 
> @DavidHuber-NOAA Definitely does seem to be a bug and may be another one in addition to what we've observed with obsproc (#691). Would you mind saving that log and noting the failure in issue #691?

@KateFriedman-NOAA Sure, I will place the log in a safe location and update that issue.
> 
> We have a branch in prepobs that we're currently using on the R&Ds post-COM-reorg: https://github.com/NOAA-EMC/prepobs/tree/feature/GFSv17_com_reorg
> 
>I'm guessing we'll need to install a copy of the updated prepobs branch (with Hercules support) on Hercules to use on Hercules or are we able to update the Orion install for use on Hercules?

I suspect we will need to have a separate install of prepobs for Hercules unless there is a way to compile without MKL, though there may be other dynamic libraries in the Intel suite that are needed and named differently between the Hercules/Orion compiler suites.  I will try disabling MKL to start and see where that gets us.

> 
> Do you mind making Hercules updates for prepobs and sending them into that `feature/GFSv17_com_reorg` branch? I'm happy to review and merge a PR if you can submit one into it. As listed in the main comment for this issue, we have a prepobs issue open for Hercules changes if needed ([NOAA-EMC/prepobs#21](https://github.com/NOAA-EMC/prepobs/issues/21)). We don't have [an obsproc issue](https://github.com/NOAA-EMC/obsproc/issues) or branch for any ports or the COM-reorg (didn't need). Don't know if we will need one for Hercules since the codes we use are in prepobs.

Sure thing!

**Comment by DavidHuber-NOAA** [comment]
So it turns out I just forgot to load the MKL module on Hercules.  The job runs mostly clean now.  I am seeing an error in the first cycle of the experiment when attempting to process TC data, but it may be expected:

```
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
           Tropical cylone relocation HAS NOT previously run
     Get global atmospheric GUESS valid for -3 hrs relative to center
                     PREPBUFR processing date/time
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
...
problem obtaining global atmos guess valid -3 hrs relative to center PREPBUFR date/time;
ABNORMAL EXIT!!!!!!!!!!!

+ 17.068s + /work/noaa/stmp/dhuber/RUNDIRS/cycled_herc2/prep.515193/err_exit

*************************************************************
** FATAL ERROR: Job prep.515193 failed
** ABNORMAL EXIT at Thu Dec 21 11:06:47 CST 2023 on hercules-01-28
*************************************************************
```
This is in lines 2233-2836 of `/work/noaa/global/dhuber/para/com/cycled_herc2/logs/2021110900/gdasprep.log`.

**Comment by KateFriedman-NOAA** [comment]
> So it turns out I just forgot to load the MKL module on Hercules.

Doing so helped us find another silent failure method so it was worth it, lol!

> I am seeing an error in the first cycle of the experiment when attempting to process TC data
This is in lines 2233-2836 of /work/noaa/global/dhuber/para/com/cycled_herc2/logs/2021110900/gdasprep.log.

I see the job struggling to find guess from the prior cycle. The 2021110900 gdasprep job needs output from the prior 18z cycle, which I don't see on disk. See lines 1995 to 2010 of the following log for an example of what should happen in that part of the prep job: `/work/noaa/stmp/kfriedma/comrot/testsruncpus/logs/2021122200/gdasprep.log`

**Comment by DavidHuber-NOAA** [comment]
@jack-woollen I have been running a test case on Hercules for 36 cycles with Fit2Obs enabled and 120 hour forecasts on the 00z cycles only.  Would you mind checking the fits?  The archived data is available in `/work/noaa/global/dhuber/archive/cycled384_herc`.

**Comment by jack-woollen** [comment]
@DavidHuber-NOAA Not being in the global group on herc, I need general read permission for your directories,

**Comment by DavidHuber-NOAA** [comment]
Apologies @jack-woollen, everything should be opened up now.

**Comment by jack-woollen** [comment]
@DavidHuber-NOAA  Dave, the fits to 00z forecasts look okay except there's no f120 (5day) fit files. Probably because that needs 126 hour forecasts for the time interpolation.

**Comment by DavidHuber-NOAA** [comment]
@jack-woollen Thanks!  Yeah, I realized that just before I asked.  I think I will go ahead with it as is just to keep things rolling.  I will likely run another long test when the gsi-monitor is enabled on the system and can retest fit2obs at that point.  Thanks again!
