### ISSUE TITLE
Wave Fix File Update

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#1604]
**Description**

To resolve issue #1493   I have created a new wave fix directory: 
/scratch1/NCEPDEV/climate/Jessica.Meixner/newfixandwavegw/wave_fix_new_20230426

This should get a new date in the fix file structure for waves as some files are renamed and others are removed.  A PR for code updates to use this new set of files will follow. 

These new files are: 

| file name | file description  | other notes | 
| ----- | ---- | ----- | 
| mesh.glo_025.nc |   mesh file for cap/cmeps for glo_025 grid  |  changed name from gefsv13_025  |
| mesh.gwes_30m.nc |   mesh file for cap/cmeps for gwes_30m grid  (used in p8) | |  
| ww3_gint.WHTGRIDINT.bin.reg025 |   ww3_gint saved binary weight file for destination grid reg025 used for HR1 | Changed name from WHTGRIDINT.bin.reg025 to add ww3_gint to name as requested |
| ww3_grid.inp.ak_10m |   Grid input file for Alaskan 10 min wave grid | | 
| ww3_grid.inp.ao_20m |  Grid input file for ArcticOcean 0.25deg | | 
| ww3_grid.inp.aoc_9km |  Grid input file for  Arctic Ocean PolarStereo 9km | | 
| ww3_grid.inp.at_10m |   Grid input file for NW Atlantic 10 min wave grid | | 
| ww3_grid.inp.ep_10m |  Grid input file for East Pacific 10 min wave grid | | 
| ww3_grid.inp.glix_10m |  Grid input file for GFSv16-wave Global 1/6 deg exchange grid | | 
| ww3_grid.inp.glo_025 |   Grid input file for  Global 0.25 masked > 82.5 N, regular lat/lon grid | Name changed from gefsv13_025 and flags were corrected| 
| ww3_grid.inp.glo_15m |  Grid input file for Global (core coverage only) of 0.25    | | 
| ww3_grid.inp.glo_15mxt |  Grid input file for GFSv16-wave Global 1/4 extended grid         | | 
| ww3_grid.inp.glo_30m |  Grid input file for Global 30 min wave grid | | 
| ww3_grid.inp.gnh_10m |  Grid input file for GFSv16-wave N Hemisphere 1/6 deg grid         | | 
| ww3_grid.inp.gsh_15m |  Grid input file for GFSv16-wave S Hemisphere 1/4 deg            | | 
| ww3_grid.inp.gwes_30m |  Grid input file for Global  30 min wave grid       | | 
| ww3_grid.inp.mx025 |  Grid input file for global 1/4 deg tripole grid lat 85 (used for HR1)    | | 
| ww3_grid.inp.points |  Grid input file for unified point output with spectral resolution for points | | 
| ww3_grid.inp.reg025 |   Grid input file for Global regular 1/4 extended grid (used for HR1)        | |
| ww3_grid.inp.rtofs_5m |  Grid input file for GFSv16-wave Global 1/12 degree ice grid         | | 
| ww3_grid.inp.so_20m |   Grid input file for Sothren Ocean 0.25deg | | 
| ww3_grid.inp.wc_10m |   Grid input file for West Coast 10 min wave grid    | | 

**Tasks**

- [x] Discuss needs with global-workflow developer assigned to request.
- [x] Add/update/remove fix file(s) in fix sets on supported platforms (global-workflow assignee task).
- [x] Update "Fix File Management" spreadsheet (https://docs.google.com/spreadsheets/d/1BeIvcz6TO3If4YCqkUK-oz_kGS9q2wTjwLS-BBemSEY/edit?usp=sharing).
- [x] Make related workflow/component updates: https://github.com/NOAA-EMC/global-workflow/pull/1605

**Comment by JessicaMeixner-NOAA** [comment]
@NeilBarton-NOAA @sbanihash  this has the updated wave input grid for GEFS, I have a PR open to use this fix file and then I'll submit a PR to @NeilBarton-NOAA PR to update to use this for GEFS.

**Comment by NeilBarton-NOAA** [comment]
@JessicaMeixner-NOAA Thanks for the heads up

**Comment by KateFriedman-NOAA** [comment]
Pulled new wave fix set into Hera `fix/wave/20230426` folder:

```
[role.glopara@hfe02 wave]$ pwd
/scratch1/NCEPDEV/global/glopara/fix/wave
[role.glopara@hfe02 wave]$ rsync -azv /scratch1/NCEPDEV/climate/Jessica.Meixner/newfixandwavegw/wave_fix_new_20230426 .
sending incremental file list
wave_fix_new_20230426/
wave_fix_new_20230426/mesh.glo_025.nc
wave_fix_new_20230426/mesh.gwes_30m.nc
wave_fix_new_20230426/ww3_gint.WHTGRIDINT.bin.reg025
wave_fix_new_20230426/ww3_grid.inp.ak_10m
wave_fix_new_20230426/ww3_grid.inp.ao_20m
wave_fix_new_20230426/ww3_grid.inp.aoc_9km
wave_fix_new_20230426/ww3_grid.inp.at_10m
wave_fix_new_20230426/ww3_grid.inp.ep_10m
wave_fix_new_20230426/ww3_grid.inp.glix_10m
wave_fix_new_20230426/ww3_grid.inp.glo_025
wave_fix_new_20230426/ww3_grid.inp.glo_15m
wave_fix_new_20230426/ww3_grid.inp.glo_15mxt
wave_fix_new_20230426/ww3_grid.inp.glo_30m
wave_fix_new_20230426/ww3_grid.inp.gnh_10m
wave_fix_new_20230426/ww3_grid.inp.gsh_15m
wave_fix_new_20230426/ww3_grid.inp.gwes_30m
wave_fix_new_20230426/ww3_grid.inp.mx025
wave_fix_new_20230426/ww3_grid.inp.points
wave_fix_new_20230426/ww3_grid.inp.reg025
wave_fix_new_20230426/ww3_grid.inp.rtofs_5m
wave_fix_new_20230426/ww3_grid.inp.so_20m
wave_fix_new_20230426/ww3_grid.inp.wc_10m

sent 55,240,623 bytes  received 438 bytes  4,091,930.44 bytes/sec
total size is 466,414,663  speedup is 8.44
[role.glopara@hfe02 wave]$ mv wave_fix_new_20230426 20230426
[role.glopara@hfe02 wave]$ chgrp global 20230426
[role.glopara@hfe02 wave]$ chgrp global 20230426/*
[role.glopara@hfe02 wave]$ ll 20230426/                                                                                                                         
total 439404
-rw-r--r-- 1 role.glopara global  58177617 Apr 26 15:06 mesh.glo_025.nc
-rw-r--r-- 1 role.glopara global  14816655 Apr 26 15:06 mesh.gwes_30m.nc
-rw-r--r-- 1 role.glopara global 143313168 Apr 26 15:06 ww3_gint.WHTGRIDINT.bin.reg025
-rw-r--r-- 1 role.glopara global   1338635 Apr 26 15:06 ww3_grid.inp.ak_10m
-rw-r--r-- 1 role.glopara global   1104932 Apr 26 15:06 ww3_grid.inp.ao_20m
-rw-r--r-- 1 role.glopara global  49254832 Apr 26 15:06 ww3_grid.inp.aoc_9km
-rw-r--r-- 1 role.glopara global   1790853 Apr 26 15:06 ww3_grid.inp.at_10m
-rw-r--r-- 1 role.glopara global   2902286 Apr 26 15:06 ww3_grid.inp.ep_10m
-rw-r--r-- 1 role.glopara global       896 Apr 26 15:06 ww3_grid.inp.glix_10m
-rw-r--r-- 1 role.glopara global  19895481 May  5 13:03 ww3_grid.inp.glo_025
-rw-r--r-- 1 role.glopara global  12271884 Apr 26 15:06 ww3_grid.inp.glo_15m
-rw-r--r-- 1 role.glopara global  16373826 Apr 26 15:06 ww3_grid.inp.glo_15mxt
-rw-r--r-- 1 role.glopara global   4613420 Apr 26 15:06 ww3_grid.inp.glo_30m
-rw-r--r-- 1 role.glopara global  14491575 Apr 26 15:06 ww3_grid.inp.gnh_10m
-rw-r--r-- 1 role.glopara global   7118472 Apr 26 15:06 ww3_grid.inp.gsh_15m
-rw-r--r-- 1 role.glopara global   4224760 Apr 26 15:06 ww3_grid.inp.gwes_30m
-rw-r--r-- 1 role.glopara global  77783358 Apr 26 15:06 ww3_grid.inp.mx025
-rw-r--r-- 1 role.glopara global       857 Apr 26 15:06 ww3_grid.inp.points
-rw-r--r-- 1 role.glopara global  16373793 Apr 26 15:06 ww3_grid.inp.reg025
-rw-r--r-- 1 role.glopara global  18667619 Apr 26 15:06 ww3_grid.inp.rtofs_5m
-rw-r--r-- 1 role.glopara global   1226584 Apr 26 15:06 ww3_grid.inp.so_20m
-rw-r--r-- 1 role.glopara global    673160 Apr 26 15:06 ww3_grid.inp.wc_10m
```

Will now rsync to other platforms...

@JessicaMeixner-NOAA The `wave_ver` in `versions/fix.ver` file will also need to be updated to the new timestamp `20230426`: https://github.com/NOAA-EMC/global-workflow/blob/develop/versions/fix.ver#L22. Can you make that change in PR #1605?

**Comment by KateFriedman-NOAA** [comment]
The new wave fix set (`20230426`) is now also in fix on Orion, Jet, and both WCOSS2s.

Showing Cactus:
```
WCOSS2 (BACKUPSYS-C) FIX> pwd
/lfs/h2/emc/global/noscrub/emc.global/FIX
WCOSS2 (BACKUPSYS-C) FIX> ll fix/wave/20230426/
total 455532
-rw-r--r-- 1 emc.global global  58177617 Apr 26 15:06 mesh.glo_025.nc
-rw-r--r-- 1 emc.global global  14816655 Apr 26 15:06 mesh.gwes_30m.nc
-rw-r--r-- 1 emc.global global 143313168 Apr 26 15:06 ww3_gint.WHTGRIDINT.bin.reg025
-rw-r--r-- 1 emc.global global   1338635 Apr 26 15:06 ww3_grid.inp.ak_10m
-rw-r--r-- 1 emc.global global   1104932 Apr 26 15:06 ww3_grid.inp.ao_20m
-rw-r--r-- 1 emc.global global  49254832 Apr 26 15:06 ww3_grid.inp.aoc_9km
-rw-r--r-- 1 emc.global global   1790853 Apr 26 15:06 ww3_grid.inp.at_10m
-rw-r--r-- 1 emc.global global   2902286 Apr 26 15:06 ww3_grid.inp.ep_10m
-rw-r--r-- 1 emc.global global       896 Apr 26 15:06 ww3_grid.inp.glix_10m
-rw-r--r-- 1 emc.global global  19895481 May  5 13:03 ww3_grid.inp.glo_025
-rw-r--r-- 1 emc.global global  12271884 Apr 26 15:06 ww3_grid.inp.glo_15m
-rw-r--r-- 1 emc.global global  16373826 Apr 26 15:06 ww3_grid.inp.glo_15mxt
-rw-r--r-- 1 emc.global global   4613420 Apr 26 15:06 ww3_grid.inp.glo_30m
-rw-r--r-- 1 emc.global global  14491575 Apr 26 15:06 ww3_grid.inp.gnh_10m
-rw-r--r-- 1 emc.global global   7118472 Apr 26 15:06 ww3_grid.inp.gsh_15m
-rw-r--r-- 1 emc.global global   4224760 Apr 26 15:06 ww3_grid.inp.gwes_30m
-rw-r--r-- 1 emc.global global  77783358 Apr 26 15:06 ww3_grid.inp.mx025
-rw-r--r-- 1 emc.global global       857 Apr 26 15:06 ww3_grid.inp.points
-rw-r--r-- 1 emc.global global  16373793 Apr 26 15:06 ww3_grid.inp.reg025
-rw-r--r-- 1 emc.global global  18667619 Apr 26 15:06 ww3_grid.inp.rtofs_5m
-rw-r--r-- 1 emc.global global   1226584 Apr 26 15:06 ww3_grid.inp.so_20m
-rw-r--r-- 1 emc.global global    673160 Apr 26 15:06 ww3_grid.inp.wc_10m
```

**Comment by KateFriedman-NOAA** [comment]
I have checked off all but the last checklist item in the main issue comment.

**Comment by JessicaMeixner-NOAA** [comment]
I have updated the wave fix version in the PR.
