### ISSUE TITLE
New set of cpl fix files 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#1645]
**Description**

This is updating the fix files for the cpl fixes.  A new date should be given to these files which can be found on hera here: 
/scratch1/NCEPDEV/climate/Jessica.Meixner/lowresgw/cplfix

This is related to providing a 5deg ocean model set-up (can't find an issue if it's there).   

The files themselves for all resolutions that we have orog data for have cpl fix files.   In each resolution directory there is a grid_spec.nc which has the file names for ocean and atm related grid files.   This adds the 5 deg ocean files and cleans up the other resolutions to only have "./" as directories. 

These files were made following instructions from Bing Fu.  This uses the make_coupler_mosaic from https://github.com/NOAA-GFDL/FRE-NCtools  

A PR will be using these new cpl fix files plus the 5deg ocean set-up. 

**Tasks**

- [x] Discuss needs with global-workflow developer assigned to request.
- [x] Add/update/remove fix file(s) in fix sets on supported platforms (global-workflow assignee task).
- [x] Update "Fix File Management" spreadsheet (https://docs.google.com/spreadsheets/d/1BeIvcz6TO3If4YCqkUK-oz_kGS9q2wTjwLS-BBemSEY/edit?usp=sharing).
- [x] Make related workflow/component updates.

**Comment by JessicaMeixner-NOAA** [comment]
Code updates can be added to: https://github.com/NOAA-EMC/global-workflow/pull/1648

**Comment by WalterKolczynski-NOAA** [comment]
@JessicaMeixner-NOAA Any idea why the grid_spec changed for resolutions we already have in fix?

```
hfe09 20220805/ > diff /scratch1/NCEPDEV/climate/Jessica.Meixner/lowresgw/cplfix /scratch1/NCEPDEV/global/glopara/fix/cpl/20220805 -r     
Binary files /scratch1/NCEPDEV/climate/Jessica.Meixner/lowresgw/cplfix/aC1152o025/grid_spec.nc and /scratch1/NCEPDEV/global/glopara/fix/cpl/20220805/aC1152o025/grid_spec.nc differ
Binary files /scratch1/NCEPDEV/climate/Jessica.Meixner/lowresgw/cplfix/aC192o050/grid_spec.nc and /scratch1/NCEPDEV/global/glopara/fix/cpl/20220805/aC192o050/grid_spec.nc differ
Only in /scratch1/NCEPDEV/global/glopara/fix/cpl/20220805: aC3072o025
Binary files /scratch1/NCEPDEV/climate/Jessica.Meixner/lowresgw/cplfix/aC384o025/grid_spec.nc and /scratch1/NCEPDEV/global/glopara/fix/cpl/20220805/aC384o025/grid_spec.nc differ
Only in /scratch1/NCEPDEV/global/glopara/fix/cpl/20220805: aC384o050
Only in /scratch1/NCEPDEV/global/glopara/fix/cpl/20220805: aC48o400
Binary files /scratch1/NCEPDEV/climate/Jessica.Meixner/lowresgw/cplfix/aC48o500/grid_spec.nc and /scratch1/NCEPDEV/global/glopara/fix/cpl/20220805/aC48o500/grid_spec.nc differ
Binary files /scratch1/NCEPDEV/climate/Jessica.Meixner/lowresgw/cplfix/aC768o025/grid_spec.nc and /scratch1/NCEPDEV/global/glopara/fix/cpl/20220805/aC768o025/grid_spec.nc differ
Only in /scratch1/NCEPDEV/global/glopara/fix/cpl/20220805: aC96o025
Binary files /scratch1/NCEPDEV/climate/Jessica.Meixner/lowresgw/cplfix/aC96o100/grid_spec.nc and /scratch1/NCEPDEV/global/glopara/fix/cpl/20220805/aC96o100/grid_spec.nc differ
Only in /scratch1/NCEPDEV/climate/Jessica.Meixner/lowresgw/cplfix: aC96o500
```

If we can ignore that, looks like we can just copy `aC96o500` into the existing set.

**Comment by WalterKolczynski-NOAA** [comment]
Nevermind, I should read the PR more carefully. Instead, is this backwards-compatible, or do we need a new fix version to update the grid spec files?

**Comment by JessicaMeixner-NOAA** [comment]
I'd recommend just starting a new version number.  They should be backwards compatible.  I do believe this does not have all the folders of resolution combinations that are in the existing folder, but there were also not orog folders for those versions that I saw (could have misread). 

So options: You can just add the new resolutions and keep the file versions the same, not replace the other files which for example have machine specific directory folders.     You could replace the grid_specs where there are now newer versions (generally wouldn't recommend, but recognize that's not my call).    Or you could just make a new date.  

If there's a resolution combination that's desired that's not in this new set, it was an oversight on my part so just let me know and I can re-make.

**Comment by JessicaMeixner-NOAA** [comment]
I just managed to unintentionally delete the contents of /scratch1/NCEPDEV/climate/Jessica.Meixner/lowresgw/cplfix

I will restore it's content immediately and report back when it's completed unless you've already copied it somewhere.

**Comment by JessicaMeixner-NOAA** [comment]
Directory restored, all contents are back in: /scratch1/NCEPDEV/climate/Jessica.Meixner/lowresgw/cplfix

**Comment by WalterKolczynski-NOAA** [comment]
Sync'd to role.glopara on Hera at `/scratch1/NCEPDEV/global/glopara/fix/cpl/20230526`

Will sync to other machines later today.

**Comment by WalterKolczynski-NOAA** [comment]
Should be everywhere now.
