### ISSUE TITLE
C96.mx500 data for orog fix files 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#1647]
**Description**

A new set of orog data was created by Sanath @sanatcumar, this can be added to the existing date of data input: 
The data is on hera here: 
/scratch2/NCEPDEV/stmp1/Sanath.Kumar/workflow_test_data/C96.mx500
The C96.mx500_frac data should be a link of this. 

Thank you to the land team who created this!   This has been tested and a PR to use this data (and the ICs also created) will shortly follow. 

**Tasks**

- [x] Discuss needs with global-workflow developer assigned to request.
- [x] Add/update/remove fix file(s) in fix sets on supported platforms (global-workflow assignee task).
- [x] Update "Fix File Management" spreadsheet (https://docs.google.com/spreadsheets/d/1BeIvcz6TO3If4YCqkUK-oz_kGS9q2wTjwLS-BBemSEY/edit?usp=sharing).
- [x] Make related workflow/component updates.

**Comment by JessicaMeixner-NOAA** [comment]
Code updates can be added to https://github.com/NOAA-EMC/global-workflow/pull/1648

**Comment by WalterKolczynski-NOAA** [comment]
Added to the existing orog set on Hera (20220805). Will sync to other platforms later today.

**Comment by WalterKolczynski-NOAA** [comment]
Should be everywhere now.
