### ISSUE TITLE
GFS v16.3.7 global_convinfo.txt

### ISSUE THREAD

**Issue by RussTreadon-NOAA** [NOAA-EMC/global-workflow#1650]
**Description**
Directory `.../fix/gsi/20230112` contains an older version of `global_convinfo.txt`.   GFS v16.3.7 placed Meteosat-10 AMVs in assimilate mode.  The EIB hosted `global_convinfo.txt` needs to be updated to the GFS v16.3.7 version.

**Tasks**
- [x] Update fix file `global_convinfo.txt` in fix sets on supported platforms
- [ ] Update "Fix File Management" spreadsheet (https://docs.google.com/spreadsheets/d/1BeIvcz6TO3If4YCqkUK-oz_kGS9q2wTjwLS-BBemSEY/edit?usp=sharing).
- [ ] Make related workflow/component updates.

**Comment by RussTreadon-NOAA** [comment]
Please refer to GSI PR [#581](https://github.com/NOAA-EMC/GSI/pull/581) for additional details.

**Comment by RussTreadon-NOAA** [comment]
The GFS v16.3.7 convinfo file to was merged into GSI-fix develop at [6a42a29](https://github.com/NOAA-EMC/GSI-fix/commit/6a42a29dbbc9fca3453cc9e829601185555890b9).   The specific convinfo file to use is linked here:  [`global_convinfo.txt`](https://github.com/NOAA-EMC/GSI-fix/blob/6a42a29dbbc9fca3453cc9e829601185555890b9/global_convinfo.txt)

**Comment by RussTreadon-NOAA** [comment]
**Note:**  This g-w issue is a **_blocker_** for GSI PR [#581](https://github.com/NOAA-EMC/GSI/pull/581).

If we opt to update `global_convinfo.txt` in the already existing `fix/gsi/20230112` directories on various machines, GSI PR [#581](https://github.com/NOAA-EMC/GSI/pull/581) can be merged into GSI `develop` without any additional changes.

If we opt to create new `fix/gsi/2023MMDD` directories on various machines, GSI PR [#581](https://github.com/NOAA-EMC/GSI/pull/581) needs to update variable `GSI_BINARY_SOURCE_DIR` in GSI modulefiles to keep GSI `develop` in sync with g-w staged fix files.

**Comment by RussTreadon-NOAA** [comment]
@WalterKolczynski-NOAA , is there any information you need from me to move forward on this issue?   GSI PR [#581](https://github.com/NOAA-EMC/GSI/pull/581) depends on closure of this issue.  I am on leave today but will check email late afternoon / evening.  Thank you for your help.

**Comment by WalterKolczynski-NOAA** [comment]
@RussTreadon-NOAA I need a place to pick up the new gsi fix directory. It will be versioned as `20230601`. We no longer overwrite files, since that defeats the purpose of the pseudo-versioning (though we will add files without new "versions" in cases where there are no overwrites).

**Comment by RussTreadon-NOAA** [comment]
@WalterKolczynski-NOAA , the updated `global_convinfo.txt` is on Hera in directory `/scratch1/NCEPDEV/da/Russ.Treadon/fix/gsi/20230601`.   

This directory was created as follows:
1. `mkdir -p /scratch1/NCEPDEV/da/Russ.Treadon/fix/gsi`
2. `cd /scratch1/NCEPDEV/da/Russ.Treadon/fix/gsi`
3. `cp -rp /scratch1/NCEPDEV/global/glopara/fix/gsi/20230112 20230601`
4. `cd 20230601`
5. `git pull`

A diff of the `20230601` and `20230112` directories, excluding `.git`, shows that only `global_convinfo.txt` differs.

```
Hera(hfe04):~$ diff -r --exclude=".git" /scratch1/NCEPDEV/global/glopara/fix/gsi/20230112 /scratch1/NCEPDEV/da/Russ.Treadon/fix/gsi/20230601
diff -r '--exclude=.git' /scratch1/NCEPDEV/global/glopara/fix/gsi/20230112/global_convinfo.txt /scratch1/NCEPDEV/da/Russ.Treadon/fix/gsi/20230601/global_convinfo.txt
125c125
<  uv       243   57   -1     3.0      0      0      0   1.5  15.0   1.4   1.5  0.055000     1  200.   100.      0    0.     2.   15   -8
---
>  uv       243   57    1     3.0      0      0      0   1.5  15.0   1.4   1.5  0.055000     1  200.   100.      0    0.     2.   15   -8
175c175
<  uv       253   57   -1     3.0      0      0      0   1.5  20.0   1.4   1.5  0.050500     1  200.   100.      0    0.     2.   15   -8
---
>  uv       253   57    1     3.0      0      0      0   1.5  20.0   1.4   1.5  0.050500     1  200.   100.      0    0.     2.   15   -8
181c181
<  uv       254   57   -1     3.0      0      0      0   1.5  20.0   1.4   1.5  0.050500     1  200.   100.      0    0.     2.   15   -8
---
>  uv       254   57    1     3.0      0      0      0   1.5  20.0   1.4   1.5  0.050500     1  200.   100.      0    0.     2.   15   -8
Hera(hfe04):~$
```
This is the correct difference.

Please copy `/scratch1/NCEPDEV/da/Russ.Treadon/fix/gsi/20230601` in its entirety (`cp -rp`) to `/scratch1/NCEPDEV/global/glopara/fix/gsi/`.   That is,

`cp -rp /scratch1/NCEPDEV/da/Russ.Treadon/fix/gsi/20230601 /scratch1/NCEPDEV/global/glopara/fix/gsi/`

**Comment by WalterKolczynski-NOAA** [comment]
Added on Hera. Will synchronize to other platforms later today. You can start creating PRs to update the version in GSI and workflow to `20230601`.

**Comment by RussTreadon-NOAA** [comment]
Thank you @WalterKolczynski-NOAA .    GSI PR [#581](https://github.com/NOAA-EMC/GSI/pull/581) has been updated to use `20230601` in `GSI_BINARY_SOURCE_DIR`.

**Comment by RussTreadon-NOAA** [comment]
@WalterKolczynski-NOAA , I successfully built the GSI on Dogwood, Hera, and Orion with the correct files copied from `GSI_BINARY_SOURCE_DIR`.   GSI PR [#581](https://github.com/NOAA-EMC/GSI/pull/581) is moving forward.

GSI files are not only staged in `GSI_BINARY_SOURCE_DIR`.  A compressed tarball is hosted in  `https://ftp.emc.ncep.noaa.gov/static_files/public/gsi`.   I logged into `emcrzdm.ncep.noaa.gov` and did a `cd /home/ftp/emc/static_files/public/gsi`.   

```
[wd20rt@vm-cprk-emcrzdm01 gsi]$ ls -l
total 1746940
-rw-r--r--. 1 rmahajan emc 1781843352 Jan 12 19:08 gsi-fix-b90f7b.tgz
```

This tarball contains binary GSI fix files.  Since this issue only changed one ASCII GSI fix file, we do not need to update `gsi-fix-b90f7b.tgz`.    I confirmed this by downloading and extracting files from the tarball.    The binary files in the tarball are identical with the binary files in `/scratch1/NCEPDEV/global/glopara/fix/gsi/20230601`.    

It seems to me that this issue may be closed.

**Comment by WalterKolczynski-NOAA** [comment]
> It seems to me that this issue may be closed.

I just finished synchronizing to all platforms, but there has been no PR to update the workflow yet. Assuming that needs to wait for the associated GSI PR to be merged.

**Comment by RussTreadon-NOAA** [comment]
@WalterKolczynski-NOAA , GSI PR [#581](https://github.com/NOAA-EMC/GSI/pull/581) will be merged once approval is given from two peer reviews.   I'll open a g-w PR to update the gsi hash after PR #[581](https://github.com/NOAA-EMC/GSI/pull/581) is merged.   The g-w PR can close this issue.  Is this the correct procedure to follow?

**Comment by WalterKolczynski-NOAA** [comment]
> @WalterKolczynski-NOAA , GSI PR [#581](https://github.com/NOAA-EMC/GSI/pull/581) will be merged once approval is given from two peer reviews. I'll open a g-w PR to update the gsi hash after PR #[581](https://github.com/NOAA-EMC/GSI/pull/581) is merged. The g-w PR can close this issue. Is this the correct procedure to follow?

Yes. When the g-w PR gets merged, please also update the fix tracking spreadsheet (listed in the first post).

I'm on leave next week, though I suspect everyone else will be wrapped up in the external review anyway. If not, Rahul may be able to approve and merge your PR. Otherwise, I will take care of it when I get back.

**Comment by RussTreadon-NOAA** [comment]
@WalterKolczynski-NOAA , here's a to-do list for remaining tasks to close this issue

1. await GSI PR [#581](https://github.com/NOAA-EMC/GSI/pull/581) approval
2. merge GSI PR [#581](https://github.com/NOAA-EMC/GSI/pull/581) into GSI `develop`
3. after GSI PR is merged, open g-w issue and associated PR to (a) change GSI hash in `Externals.cfg` and `sorc/checkout.sh` and (b) set `gsi_ver=20230601` in `versions/fix.ver`
4. request g-w PR review from Walter and/or Rahul
5. await approval and merger of g-w PR into `develop`
6. after g-w PR is merged, replace `20230112` with `20230601` in cell B17 of google sheet [Fix File Management](https://docs.google.com/spreadsheets/d/1BeIvcz6TO3If4YCqkUK-oz_kGS9q2wTjwLS-BBemSEY/edit#gid=526608225)
7. close this issue

Did I miss anything?

**Comment by WalterKolczynski-NOAA** [comment]
@RussTreadon-NOAA That look complete. Thanks. Still new to the details of the fix file management stuff myself.

**Comment by RussTreadon-NOAA** [comment]
Thanks @WalterKolczynski-NOAA for the confirmation.  I, too, am new to fix file management.   Enjoy your leave.

**Comment by RussTreadon-NOAA** [comment]
GSI PR [#581](https://github.com/NOAA-EMC/GSI/pull/581) merged into [NOAA-EMC/GSI](https://github.com/NOAA-EMC/GSI) [`develop`](https://github.com/NOAA-EMC/GSI/tree/develop).  Done at GSI hash [8735959](https://github.com/NOAA-EMC/GSI/commit/8735959064c3661a85b16328cb0bfc0cd546bc09).
