### ISSUE TITLE
Add Fix files for low-res wave model 

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#1652]
**Description**

Adding two low resolution options for the wave model (issue #1333) which requires fix file additions: 

Global 2 degree, new fix files for grid input and corresponding netcdf mesh file: 
/scratch1/NCEPDEV/climate/Jessica.Meixner/newfixandwavegw/wave_fix_new_20230510/ww3_grid.inp.glo_200
/scratch1/NCEPDEV/climate/Jessica.Meixner/newfixandwavegw/wave_fix_new_20230510/mesh.glo_200.nc

Global 5 degree, new fix files for grid input and corresponding netcdf mesh file: 
/scratch1/NCEPDEV/climate/Jessica.Meixner/newfixandwavegw/wave_fix_new_20230510/ww3_grid.inp.glo_500
/scratch1/NCEPDEV/climate/Jessica.Meixner/newfixandwavegw/wave_fix_new_20230510/mesh.glo_500.nc

These are just new files, no new date/version for the fix files are needed.   A PR enabling the use of these files will be ready soon. 

**Tasks**

- [x] Discuss needs with global-workflow developer assigned to request.
- [x] Add/update/remove fix file(s) in fix sets on supported platforms (global-workflow assignee task).
- [x] Update "Fix File Management" spreadsheet (https://docs.google.com/spreadsheets/d/1BeIvcz6TO3If4YCqkUK-oz_kGS9q2wTjwLS-BBemSEY/edit?usp=sharing).
- [x] Make related workflow/component updates.

**Comment by JessicaMeixner-NOAA** [comment]
Code updates to use these fix files are here: https://github.com/NOAA-EMC/global-workflow/pull/1653

**Comment by WalterKolczynski-NOAA** [comment]
Files added to fix/wave/20230426 on Hera. Synchronization to other machines will happen soon.

**Comment by WalterKolczynski-NOAA** [comment]
Should be everywhere now.
