### ISSUE TITLE
Fix file update for C192mx025

### ISSUE THREAD

**Issue by JessicaMeixner-NOAA** [NOAA-EMC/global-workflow#1770]
**Description**
Here are the requested C192mx025 oro files (https://github.com/NOAA-EMC/global-workflow/issues/1730#issuecomment-1625549037) provided by Sanath Kumar
There are no related workflow or component changes needed. 
Pick-up location: /scratch1/NCEPDEV/climate/Jessica.Meixner/FromSanath/C192.mx025 

**Tasks**

- [x] Discuss needs with global-workflow developer assigned to request.
- [x] Add/update/remove fix file(s) in fix sets on supported platforms (global-workflow assignee task).
- [ ] Update "Fix File Management" spreadsheet (https://docs.google.com/spreadsheets/d/1BeIvcz6TO3If4YCqkUK-oz_kGS9q2wTjwLS-BBemSEY/edit?usp=sharing).
- [ ] Make related workflow/component updates.

**Comment by WalterKolczynski-NOAA** [comment]
Files have been added to the master fix on all machines except Jet (disk is full).

**Comment by WalterKolczynski-NOAA** [comment]
Thanks for providing these @JessicaMeixner-NOAA and Sanath
