### ISSUE TITLE
GFSv16.3.9 - temporary satingest changes for NOAA-21

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#1813]
**Description**
Email from @ADCollard 

> I need to update GFS at that time to turn off NOAA-21 ingest as the CRTM is still causing issues (and August 29 is when the satingest upgrade will start the NOAA-21 data flow).
I think I have been given the green light from Steven Earle to turn on NOAA-20 OMPS and PlanetIQ on August 29.

Production update sliding in before planned v16.3.8 (now v16.3.9). Some changes already made in PR #1804. Additional updates needed to resolve build issue with tropcy (issue #1812). See https://github.com/NOAA-EMC/GSI/pull/611

**Workflow Changes**
Version updates, new release notes, fix for tropcy build.

**Tasks**
- [x] Create release branch (https://github.com/NOAA-EMC/global-workflow/tree/release/gfs.v16.3.8)
- [x] Mention gfs_bufr -check all bugzilla fix in release notes. https://github.com/NOAA-EMC/global-workflow/pull/1814
- [x] New GSI tag ([gfsda.v16.3.8](https://github.com/NOAA-EMC/GSI/releases/tag/gfsda.v16.3.8)) PR #1804
- [x] Fix tropcy build issue with w3nco error https://github.com/NOAA-EMC/global-workflow/pull/1815
- [x] Update release notes PR #1804
- [x] Cut hand-off tag for CDF @WalterKolczynski-NOAA 
- [x] Submit CDF to NCO @ADCollard 
- [x] Implementation into operations complete (implemented 9/11 during 12z cycle)
- [x] Merge release branch into operational branch (https://github.com/NOAA-EMC/global-workflow/pull/1852)
- [x] Cut version tag from operational branch (https://github.com/NOAA-EMC/global-workflow/releases/tag/gfs.v16.3.9)
- [x] Release new version tag (https://github.com/NOAA-EMC/global-workflow/releases/tag/gfs.v16.3.9)
- [x] Update Read-The-Docs operations status version in `develop` (https://github.com/NOAA-EMC/global-workflow/pull/1853)

**Comment by RussTreadon-NOAA** [comment]
g-w [release/gfs.v16.3.8](https://github.com/NOAA-EMC/global-workflow/tree/release/gfs.v16.3.8) installed on Cactus.  The 20230822 00Z gdas cycle is being run to confirm installation works as intended.  The gsi and enkf analyses are complete.  Results have been examined by DA staff and expected changes are present.

**Comment by KateFriedman-NOAA** [comment]
This change is planned to go into ops Monday 9/11 at 1430z. Now v16.3.9.

**Comment by KateFriedman-NOAA** [comment]
RFC Memo from 9/8/23:
```
RFC 11522 - On WCOSS2, upgrade the GFS to v16.3.8, which includes the
following:

○ turns off ingest of NOAA-21 radiances into the GSI,
○ PlanetIQ GPSRO and NOAA-20 OMPS (Ozone Mapping
and Profiler Suite) Ozone retrievals will be actively
assimilated,
○ OMPS observation errors will be adjusted.
To be implemented on September 11, 1430Z to 1900Z.
``
Mentions it as version v16.3.8 but it's now v16.3.9 due to ARFC a couple days before.

**Comment by KateFriedman-NOAA** [comment]
SPA Simon Hsiao confirmed v16.3.9 was just implemented for the 12z cycle.

**Comment by KateFriedman-NOAA** [comment]
Renamed release branch to reflect new version ([release/gfs.v16.3.9](https://github.com/NOAA-EMC/global-workflow/tree/release/gfs.v16.3.9)).

**Comment by KateFriedman-NOAA** [comment]
Implemented, release branch merged into `dev/gfs.v16` branch, tag cut, RTD updated. This upgrade is complete.
