### ISSUE TITLE
GFSv16.3.10 - Annual CO2 fix file update for 2024

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#1924]
### Description

@Qingfu-Liu has provided information for the annual CO2 fix file update for 2024. New fix files will be added to the production GFS and also need to be pulled into the developmental fix file set on supported platforms.

Release notes: https://docs.google.com/document/d/1cxcxj5-8CPUfW1nQo2E4q7rQVny9EIEc/edit

New files:
```
kate.friedman@clogin07:~> diff -r /lfs/h2/emc/physics/noscrub/qingfu.liu/CO2_for_NCO_2024/gfs.v16.3.10/fix/fix_am/co2dat_4a /lfs/h1/ops/prod/packages/gfs.v16.3.9/fix/fix_am/co2dat_4a
Only in /lfs/h2/emc/physics/noscrub/qingfu.liu/CO2_for_NCO_2024/gfs.v16.3.10/fix/fix_am/co2dat_4a: global_co2historicaldata_2022.txt
Only in /lfs/h2/emc/physics/noscrub/qingfu.liu/CO2_for_NCO_2024/gfs.v16.3.10/fix/fix_am/co2dat_4a: global_co2historicaldata_2023.txt_proj_u
Only in /lfs/h2/emc/physics/noscrub/qingfu.liu/CO2_for_NCO_2024/gfs.v16.3.10/fix/fix_am/co2dat_4a: global_co2historicaldata_2024.txt_proj
```
```
kate.friedman@clogin07:~> diff -r /lfs/h2/emc/physics/noscrub/qingfu.liu/CO2_for_NCO_2024/gfs.v16.3.10/fix/fix_am/fix_co2_proj /lfs/h1/ops/prod/packages/gfs.v16.3.9/fix/fix_am/fix_co2_proj
Only in /lfs/h2/emc/physics/noscrub/qingfu.liu/CO2_for_NCO_2024/gfs.v16.3.10/fix/fix_am/fix_co2_proj: global_co2historicaldata_2024.txt
```
```
kate.friedman@clogin07:~> diff -r /lfs/h2/emc/physics/noscrub/qingfu.liu/CO2_for_NCO_2024/gfs.v16.3.10/fix/fix_am/fix_co2_update /lfs/h1/ops/prod/packages/gfs.v16.3.9/fix/fix_am/fix_co2_update
Only in /lfs/h2/emc/physics/noscrub/qingfu.liu/CO2_for_NCO_2024/gfs.v16.3.10/fix/fix_am/fix_co2_update: global_co2historicaldata_2023.txt
```

### Target version

v16.3.10? TBD

### Expected workflow changes

If version different from upgrade outlined in #1356 then will update `gfs_ver` in system. Awaiting feedback from NCO on how they will implement this with regards to the GSI/obsproc update already submitted.

## TO DO

- [x] Pull new files into GFSv16 `fix_nco_gfsv16.3.0` set on both WCOSS2s
- [x] Rsync new files into GFSv16 `fix_nco_gfsv16.3.0` set on Hera
- [x] Rsync new files into GFSv16 `fix_nco_gfsv16.3.0` set on Orion
- [x] Pull new files in developmental GFSv17 fix set on both WCOSS2s
- [x] Rsync new files into developmental GFSv17 fix set on Hera
- [x] Rsync new files into developmental GFSv17 fix set on Orion
- [x] Rsync new files into developmental GFSv17 fix set on Jet
- [x] Update fix am tarball on HPSS
- [x] Create release branch (`release/gfs.v16.3.10`)
- [x] Add release notes to release branch - #1950 
- [x] Update GFS version to v16.3.10 in `run.ver` - #1950 
- [x] Cut `EMC-v16.3.10` hand-off tag - https://github.com/NOAA-EMC/global-workflow/releases/tag/EMC-v16.3.10
- [x] Implemented into operations
- [x] Merge release branch into `dev/gfs.v16` branch (#1955)
- [x] Cut `gfs.v16.3.10` tag
- [x] Release `gfs.v16.3.10` tag (https://github.com/NOAA-EMC/global-workflow/releases/tag/gfs.v16.3.10)
- [x] Announce to users
- [x] Update Read-The-Docs operations status version in develop (#1976)

**Comment by KateFriedman-NOAA** [comment]
Will be v16.3.10 in ops.

**Comment by KateFriedman-NOAA** [comment]
@WalterKolczynski-NOAA Can you update the `fix_nco_gfsv16.3.0` and `fix` sets on Orion? Note, I converted the `fix_nco_gfsv16.3.0` fix copy from mostly symlinks (that pointed to the `fix_nco_gfsv16` set) to actual files, so you'll see the whole `fix_nco_gfsv16.3.0` set come over in an rsync. Thanks!

**Comment by WalterKolczynski-NOAA** [comment]
Orion is updated.

**Comment by KateFriedman-NOAA** [comment]
Thanks @WalterKolczynski-NOAA !

**Comment by KateFriedman-NOAA** [comment]
NCO slated this for implementation 10/23.

**Comment by KateFriedman-NOAA** [comment]
From the October 20th RFC Memo:
```
RFC 11726 - On WCOSS2, install the 2024 carbon dioxide (CO2) fix file updates
for several model packages. The GFS, GEFS, NAM, SREF, HIRESW, HMON,
HAFS, CFS, and CFS_HUR models rely on the historical/projected global CO2
abundance data in their forecasts. To be implemented on October 23, 1145Z to
1930Z.
```

**Comment by KateFriedman-NOAA** [comment]
New tarball of `fix/am` created on HPSS with updated CO2 fix files within: 
`/5year/NCEPDEV/emc-global/emc.glopara/fix/fix.am.20220805.tar.xz.idx`.
```
[role.glopara@hfe02 fix]$ hpsstar dir /5year/NCEPDEV/emc-global/emc.glopara/fix | grep am
[connecting to hpsscore1.fairmont.rdhpcs.noaa.gov/1217]
-rw-r--r--    1 role.glopara  emc-global  1670122664 Oct 31 17:15 fix.am.20220805.tar.xz
```

**Comment by KateFriedman-NOAA** [comment]
This issue/update is now complete. Closing.
