### ISSUE TITLE
Create separate tracker and genesis jobs

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#1988]
### What new functionality do you need?

The tracker and genesis jobs currently run within the vrfy job. They need to be their own separate jobs. Break them out of the vrfy job as part of work for issue #235.

### What are the requirements for the new functionality?

New, separate, toggle-able jobs in the rocoto mesh for each tracker and genesis job.

### Acceptance Criteria

Three new functional jobs.

### TO DO

- [x] Remove tracker and genesis jobs from vrfy job
- [x] Remove tracker and genesis settings from `config.vrfy`
- [x] Create rocoto job scripts for tracker and genesis
- [x] Create configs for tracker and genesis
- [x] Add tracker and genesis jobs to setup scripts
- [x] Add tracker and genesis jobs to resources
- [x] Reduce `vrfy` job walltime

**Comment by KateFriedman-NOAA** [comment]
Test of newly separated tracker and genesis jobs on WCOSS2 successful and reproducing control run of `develop`:
```
kate.friedman@clogin07:/lfs/h2/emc/ptmp/kate.friedman/comrot/testtrackgen> ll gfs.20211221/00/products/atmos/cyclone/*
gfs.20211221/00/products/atmos/cyclone/genesis_vital:
total 36
-rw-r--r-- 1 kate.friedman emc     0 Nov  8 22:28 all.vitals.gfs.gfso.2021
-rw-r--r-- 1 kate.friedman emc  1746 Nov  8 22:32 storms.gfso.atcf_gen.2021122100
-rw-r--r-- 1 kate.friedman emc 15132 Nov  8 22:32 storms.gfso.atcf_gen.altg.2021122100
-rw-r--r-- 1 kate.friedman emc   576 Nov  8 22:32 trak.gfso.atcfunix.2021122100
-rw-r--r-- 1 kate.friedman emc  8840 Nov  8 22:32 trak.gfso.atcfunix.altg.2021122100

gfs.20211221/00/products/atmos/cyclone/tracks:
total 12
-rw-r--r-- 1 kate.friedman emc 7453 Nov  8 22:25 avnop.t00z.cyclone.trackatcfunix
-rw-r--r-- 1 kate.friedman emc 3277 Nov  8 22:25 avno.t00z.cyclone.trackatcfunix
kate.friedman@clogin07:/lfs/h2/emc/ptmp/kate.friedman/comrot/testtrackgen> ll ../ctrltrackgen/gfs.20211221/00/products/atmos/cyclone/*
../ctrltrackgen/gfs.20211221/00/products/atmos/cyclone/genesis_vital:
total 36
-rw-r--r-- 1 kate.friedman emc     0 Nov  8 22:29 all.vitals.gfs.gfso.2021
-rw-r--r-- 1 kate.friedman emc  1746 Nov  8 22:32 storms.gfso.atcf_gen.2021122100
-rw-r--r-- 1 kate.friedman emc 15132 Nov  8 22:32 storms.gfso.atcf_gen.altg.2021122100
-rw-r--r-- 1 kate.friedman emc   576 Nov  8 22:32 trak.gfso.atcfunix.2021122100
-rw-r--r-- 1 kate.friedman emc  8840 Nov  8 22:32 trak.gfso.atcfunix.altg.2021122100

../ctrltrackgen/gfs.20211221/00/products/atmos/cyclone/tracks:
total 12
-rw-r--r-- 1 kate.friedman emc 7453 Nov  8 22:25 avnop.t00z.cyclone.trackatcfunix
-rw-r--r-- 1 kate.friedman emc 3277 Nov  8 22:25 avno.t00z.cyclone.trackatcfunix
kate.friedman@clogin07:/lfs/h2/emc/ptmp/kate.friedman/comrot/testtrackgen> cmp ../ctrltrackgen/gfs.20211221/00/products/atmos/cyclone/tracks/avnop.t00z.cyclone.trackatcfunix gfs.20211221/00/products/atmos/cyclone/tracks/avnop.t00z.cyclone.trackatcfunix 
kate.friedman@clogin07:/lfs/h2/emc/ptmp/kate.friedman/comrot/testtrackgen> cmp ../ctrltrackgen/gfs.20211221/00/products/atmos/cyclone/tracks/avno.t00z.cyclone.trackatcfunix gfs.20211221/00/products/atmos/cyclone/tracks/avno.t00z.cyclone.trackatcfunix 
kate.friedman@clogin07:/lfs/h2/emc/ptmp/kate.friedman/comrot/testtrackgen> cmp ../ctrltrackgen/gfs.20211221/00/products/atmos/cyclone/genesis_vital/storms.gfso.atcf_gen.2021122100 gfs.20211221/00/products/atmos/cyclone/genesis_vital/storms.gfso.atcf_gen.2021122100 
kate.friedman@clogin07:/lfs/h2/emc/ptmp/kate.friedman/comrot/testtrackgen> cmp ../ctrltrackgen/gfs.20211221/00/products/atmos/cyclone/genesis_vital/storms.gfso.atcf_gen.altg.2021122100 gfs.20211221/00/products/atmos/cyclone/genesis_vital/storms.gfso.atcf_gen.altg.2021122100 
kate.friedman@clogin07:/lfs/h2/emc/ptmp/kate.friedman/comrot/testtrackgen> cmp ../ctrltrackgen/gfs.20211221/00/products/atmos/cyclone/genesis_vital/trak.gfso.atcfunix.2021122100 gfs.20211221/00/products/atmos/cyclone/genesis_vital/trak.gfso.atcfunix.2021122100 
kate.friedman@clogin07:/lfs/h2/emc/ptmp/kate.friedman/comrot/testtrackgen> cmp ../ctrltrackgen/gfs.20211221/00/products/atmos/cyclone/genesis_vital/trak.gfso.atcfunix.altg.2021122100 gfs.20211221/00/products/atmos/cyclone/genesis_vital/trak.gfso.atcfunix.altg.2021122100 
kate.friedman@clogin07:/lfs/h2/emc/ptmp/kate.friedman/comrot/testtrackgen> 
```

Both the control and test runs picked up Typhoon Rai in the western pacific:
```
kate.friedman@clogin07:/lfs/h2/emc/ptmp/kate.friedman/comrot/testtrackgen> cat /lfs/h1/ops/prod/com/gfs/v16.3/syndat/syndat_tcvitals.2021 | grep 20211221
JTWC 28W RAI       20211221 0000 210N 1142E 040 062 1007 1011 0185 15 064 -999 -999 -999 -999 S
JTWC 94B INVEST    20211221 0000 058N 0968E 080 037 1008 1012 0259 13 055 -999 -999 -999 -999 S
JTWC 28W RAI       20211221 0000 210N 1142E 040 062 1007 1011 0185 15 064 -999 -999 -999 -999 S
JTWC 94B INVEST    20211221 0000 058N 0968E 080 037 1008 1012 0259 13 055 -999 -999 -999 -999 S
JTWC 28W RAI       20211221 0000 210N 1142E 040 062 1007 1011 0185 15 064 -999 -999 -999 -999 S
JTWC 94B INVEST    20211221 0000 058N 0968E 080 037 1008 1012 0259 13 055 -999 -999 -999 -999 S
JTWC 28W RAI       20211221 0000 210N 1142E 040 062 1007 1011 0185 15 064 -999 -999 -999 -999 S
JTWC 94B INVEST    20211221 0000 058N 0968E 080 037 1008 1012 0259 13 055 -999 -999 -999 -999 S
JTWC 28W RAI       20211221 0600 215N 1152E 050 067 1007 1011 0185 15 064 -999 -999 -999 -999 S
JTWC 28W RAI       20211221 0600 215N 1152E 050 067 1007 1011 0185 15 064 -999 -999 -999 -999 S
JTWC 28W RAI       20211221 0600 215N 1152E 050 067 1007 1011 0185 15 064 -999 -999 -999 -999 S
JTWC 28W RAI       20211221 0600 215N 1152E 050 067 1007 1011 0185 15 064 -999 -999 -999 -999 S
JTWC 28W RAI       20211221 1200 217N 1165E 060 067 1007 1011 0185 15 064 -999 -999 -999 -999 S
JTWC 28W RAI       20211221 1200 217N 1165E 060 067 1007 1011 0185 15 064 -999 -999 -999 -999 S
JTWC 28W RAI       20211221 1200 217N 1165E 060 067 1007 1011 0185 15 064 -999 -999 -999 -999 S
JTWC 28W RAI       20211221 1200 217N 1165E 060 067 1007 1011 0185 15 064 -999 -999 -999 -999 S
kate.friedman@clogin07:/lfs/h2/emc/ptmp/kate.friedman/comrot/testtrackgen> cat gfs.20211221/00/products/atmos/cyclone/tracks/avno.t00z.cyclone.trackatcfunix              
WP, 28, 2021122100, 03, AVNO, 000, 210N, 1137E,  22, 1010, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99, 108
BB, 94, 2021122100, 03, AVNO, 000,  56N,  988E,  11, 1010, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99,  93
WP, 28, 2021122100, 03, AVNO, 006, 219N, 1151E,  21, 1010, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99,  21
BB, 94, 2021122100, 03, AVNO, 006,  58N,  993E,  13, 1010, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99,  95
WP, 28, 2021122100, 03, AVNO, 012, 228N, 1176E,  23, 1012, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99, 152
BB, 94, 2021122100, 03, AVNO, 012,  59N,  993E,  12, 1010, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99,  82
WP, 28, 2021122100, 03, AVNO, 018, 248N, 1210E,  27, 1011, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99,  55
BB, 94, 2021122100, 03, AVNO, 018,  58N,  993E,  11, 1011, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99, 129
WP, 28, 2021122100, 03, AVNO, 024, 258N, 1241E,  29, 1012, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99, 125
BB, 94, 2021122100, 03, AVNO, 024,  57N,  993E,  11, 1010, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99, 157
WP, 28, 2021122100, 03, AVNO, 030, 257N, 1260E,  32, 1009, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99, 120
BB, 94, 2021122100, 03, AVNO, 030,  53N,  996E,  14, 1009, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99, 141
WP, 28, 2021122100, 03, AVNO, 036, 247N, 1264E,  29, 1013, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99, 157
BB, 94, 2021122100, 03, AVNO, 036,  51N,  999E,  10, 1009, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99, 161
WP, 28, 2021122100, 03, AVNO, 042, 241N, 1253E,  26, 1012, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99,  51
BB, 94, 2021122100, 03, AVNO, 042,  63N, 1002E,  11, 1010, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99, 137
WP, 28, 2021122100, 03, AVNO, 048, 240N, 1253E,  24, 1013, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99,  56
WP, 28, 2021122100, 03, AVNO, 054, 244N, 1258E,  22, 1011, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99,  73
WP, 28, 2021122100, 03, AVNO, 060, 249N, 1264E,  20, 1013, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99, 159
WP, 28, 2021122100, 03, AVNO, 066, 257N, 1265E,  18, 1011, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99, 149
WP, 28, 2021122100, 03, AVNO, 072, 264N, 1273E,  18, 1012, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99, 152
WP, 28, 2021122100, 03, AVNO, 078, 281N, 1297E,  20, 1010, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99, 145
WP, 28, 2021122100, 03, AVNO, 084, 291N, 1324E,  21, 1011, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99, 158
WP, 28, 2021122100, 03, AVNO, 090, 300N, 1339E,  23, 1010, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99, 150
WP, 28, 2021122100, 03, AVNO, 096, 311N, 1372E,  26, 1010, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99, 155
WP, 28, 2021122100, 03, AVNO, 102, 328N, 1414E,  29, 1005, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99, 154
WP, 28, 2021122100, 03, AVNO, 108, 337N, 1463E,  29, 1005, XX,  34, NEQ, 0000, 0000, 0000, 0000,  -99,  -99, 161
WP, 28, 2021122100, 03, AVNO, 114, 341N, 1526E,  38, 1002, XX,  34, NEQ, 0000, 0256, 0186, 0000,  -99,  -99, 152
WP, 28, 2021122100, 03, AVNO, 120, 341N, 1594E,  36, 1002, XX,  34, NEQ, 0259, 0185, 0262, 0000,  -99,  -99,  64
```

**Comment by KateFriedman-NOAA** [comment]
The FSU genesis job is not tested for this issue. It is not currently turned on in `develop` and will remain turned off for this issue's work. There will be a follow-up issue/PR to test the tracker/genesis jobs with finalized COM reorg updates to tracker repository. Can test FSU genesis job then.
