### ISSUE TITLE
GFSv16.3.12 - Turn on active assimilation of NOAA-21 radiances

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#2096]
### Description

This operational update will turn on the active assimilation of NOAA-21 radiances. This is a companion update to the previous GFSv16.3.11 upgrade that turned on passive monitoring of NOAA-21 radiances.

### Target version

v16.3.12

### Tasks

- [x] Create release branch (`release/gfs.v16.3.12`)
- [x] New GSI tag (update `Externals.cfg` and `sorc/checkout.sh`
- [x] Update`gfs_ver=v16.3.12` and `version=v16.3.12` in `versions/run.ver` (and mention in release notes)
- [x] Create/add new release notes
- [x] Cut hand-off tag for CDF (`EMC-v16.3.12`)
- [x] Submit CDF to NCO
- [x] Implementation into operations complete
- [x] Merge release branch into operational branch - https://github.com/NOAA-EMC/global-workflow/pull/2167
- [x] Cut version tag from operational branch
- [x] Release new version tag
- [x] Announce to users
- [x] Update Read-The-Docs operations status version in develop - #2169

**Comment by RussTreadon-NOAA** [comment]
NOAA-EMC/GSI tag [`gfsda.v16.3.12`](https://github.com/NOAA-EMC/GSI/releases/tag/gfsda.v16.3.12) created (see GSI PR [#660](https://github.com/NOAA-EMC/GSI/pull/660)).

**Comment by KateFriedman-NOAA** [comment]
Release branch initiated (cut from `release/gfs.v16.3.11` branch after WAFS update was removed): https://github.com/NOAA-EMC/global-workflow/tree/release/gfs.v16.3.12

A PR with changes for GFSv16.3.12 can now be sent to the `release/gfs.v16.3.12` branch.

**Comment by KateFriedman-NOAA** [comment]
Updated checklist in main issue comment to note expected updates in this branch.

**Comment by KateFriedman-NOAA** [comment]
@ADCollard Tag has been cut for hand-off: https://github.com/NOAA-EMC/global-workflow/releases/tag/EMC-v16.3.12

**Comment by ADCollard** [comment]
Thank you!  I will check this all compiles and runs and then submit the CDF.  Although, given the other conversation with Steven et al this might end up being v16.3.11!

**Comment by ADCollard** [comment]
@KateFriedman-NOAA @aerorahul Continuing tests indicate that the 24GB memory allocation for ediag is barely being exceeded on occasion causing a failure in the eupd step (not in ediag!).  Two questions:

1) Where should I change this so NCO's ecflow picks up this change.  In config.resources.nco.static ?
2) Is there a preferred increment in memory usage?  Should I just double it (so it's consistent with gdasanaldiag)?

**Comment by KateFriedman-NOAA** [comment]
> 1. Where should I change this so NCO's ecflow picks up this change.  In config.resources.nco.static ?

@ADCollard Update the following to adjust the memory request for the ediag job:

1. The end of this line to adjust the memory value for ecflow:
https://github.com/NOAA-EMC/global-workflow/blob/release/gfs.v16.3.12/ecf/scripts/enkfgdas/analysis/create/jenkfgdas_diag.ecf#L7

2. This line in `config.resources.nco.static`: https://github.com/NOAA-EMC/global-workflow/blob/release/gfs.v16.3.12/parm/config/config.resources.nco.static#L277

3. And this line in `config.resource.emc.dyn` (for consistency): https://github.com/NOAA-EMC/global-workflow/blob/release/gfs.v16.3.12/parm/config/config.resources.emc.dyn#L341

> Is there a preferred increment in memory usage? Should I just double it (so it's consistent with gdasanaldiag)?

Generally just depends on what the job needs (based on trial and error at times) or what the component developers feel is appropriate. Doubling it to match the value that analdiag uses seems reasonable since the two jobs are related. The job only uses one node with plenty of untapped memory so increasing to 48GB seems fine to me.

Please send a PR into the `release/gfs.v16.3.12` branch and I can merge it and cut a new tag to have it updated on our end.

Will NCO be testing the new memory in para?

**Comment by ADCollard** [comment]
Thanks @KateFriedman-NOAA These changes have been add to PR #2112

**Comment by KateFriedman-NOAA** [comment]
Merged #2112 and synced release branch with WAFS update in GFSv16.3.11 release branch and recut EMC-v16.3.12 tag.

**Comment by KateFriedman-NOAA** [comment]
@ADCollard Do you happen to have a target implementation date from NCO for this yet? Thanks!

**Comment by ADCollard** [comment]
> @ADCollard Do you happen to have a target implementation date from NCO for this yet? Thanks!

@KateFriedman-NOAA I am being told 2023121812, but we shall see!

**Comment by KateFriedman-NOAA** [comment]
> I am being told 2023121812, but we shall see!

Good to know, thanks @ADCollard !

**Comment by KateFriedman-NOAA** [comment]
RFC memo December 15th:
```
RFC 12011 - On WCOSS2, fix files ‘global_satinfo.tx’t and ‘global_convinfo.txt’
are being updated to begin actively assimilating NOAA-21 radiances into the
GFS. To be implemented on December 18, 1430Z to 1630Z.
```

**Comment by KateFriedman-NOAA** [comment]
@ADCollard Are we done archiving the experimental ATMS/CRIS dump files or does that need to continue?

**Comment by ADCollard** [comment]
@KateFriedman-NOAA ATMS and CrIS are operationally dumped now, so archiving the experimental files should no longer be required.

**Comment by KateFriedman-NOAA** [comment]
Thanks for confirming @ADCollard ! I have discontinued the experimental dump pickup/archival. @SudhirNadiga-NOAA you can stop dumping the experimental files if you haven't already, thanks!

**Comment by SudhirNadiga-NOAA** [comment]
Thanks @KateFriedman-NOAA and @ADCollard I will stop my cron when Dogwood returns. @ilianagenkova please note this change.
