### ISSUE TITLE
Upgrade to Intel LLVM Compilers

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow#2122]
### What new functionality do you need?

All subcomponents should be upgraded to Intel LLVM compilers.  Module files should be upgraded as appropriate to accommodate the new compilers.

### What are the requirements for the new functionality?

- [ ] UFS https://github.com/ufs-community/ufs-weather-model/issues/2025
- [ ] UFS_Utils https://github.com/ufs-community/UFS_UTILS/issues/879
- [ ] GSI https://github.com/NOAA-EMC/GSI/issues/665
- [ ] GDASApp https://github.com/NOAA-EMC/GDASApp/issues/794
- [ ] GSI-Utils https://github.com/NOAA-EMC/GSI-utils/issues/21
- [ ] GSI-Monitor https://github.com/NOAA-EMC/GSI-Monitor/issues/105
- [ ] GFS-Utils https://github.com/NOAA-EMC/gfs-utils/issues/37

Testing will be required to find out if LLVM compilers are compatible with libraries compiled with classic compilers.  If not, then a spack-stack build with LLVM compilers will be needed.  This would require multiple libraries be updated to the LLVM suite.  For instance:
- [ ] NCEPLIBS-BUFR (for instance, BUFR https://github.com/NOAA-EMC/NCEPLIBS-bufr/issues/538)

### Acceptance Criteria

All jobs are able to run to completion and match classic compiler results (within acceptable limits).
