### ISSUE TITLE
Upgrade to spack-stack 1.6.0

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow#2195]
### What new functionality do you need?

The GSI should be upgraded to use the newest suite of spack-stack libraries (version 1.6.0). This includes an upgrade of CRTM to 2.4.0.1, netcdf-fortran to 4.6.1, prod_util to 2.1.1, and Python to 3.11.6.

### What are the requirements for the new functionality?

The following submodules need to be upgraded as well, though this can be an incremental process:

- [ ] UFS https://github.com/ufs-community/ufs-weather-model/issues/2091
- [ ] UFS_Utils https://github.com/ufs-community/UFS_UTILS/issues/884
- [ ] GSI https://github.com/NOAA-EMC/GSI/issues/674
- [ ] GSI-Utils https://github.com/NOAA-EMC/GSI-utils/issues/26
- [ ] GSI-Monitor https://github.com/NOAA-EMC/GSI-Monitor/issues/109
- [ ] GDASApp https://github.com/NOAA-EMC/GDASApp/issues/833
- [ ] UPP https://github.com/NOAA-EMC/UPP/issues/844
- [ ] GFS-Utils https://github.com/NOAA-EMC/gfs-utils/issues/40
- [ ] EMC_Verif-global https://github.com/NOAA-EMC/EMC_verif-global/issues/117

### Acceptance Criteria

All upgraded components are made compatible with the global workflow and produce similar results with any expected differences defined (e.g. due to the CRTM upgrade).

### Suggest a solution (optional)

Upgrade each of the submodules to spack-stack/1.6.0 and simultaneously upgrade the global workflow modules to 1.6.0.  Ideally, it would be nice to have the UFS, GSI, UFS_Utils, and UPP upgraded before upgrading the global workflow and simultaneously upgrading GSI-utils and GSI-monitor.  The GDASApp and EMC_Verif-global repositories can be upgraded at a later time.

**Comment by DavidHuber-NOAA** [comment]
Spack-stack 1.6.0 has now been installed on all platforms.

**Comment by malloryprow** [comment]
I think I have a branch with changes for EMC_verif-global ready. A few other metp realted files in the g-w would need to but updated too. Obviously we will need to go some testing, and it will probably need some changes but let me know if/when you would like to test.

**Comment by DavidHuber-NOAA** [comment]
@malloryprow The UFS is going through its upgrade to 1.6.0 now, so I am starting work on this myself.  Hopefully I will have something we can test against by next week.
