### ISSUE TITLE
Convert forecast-only stage_ic job to python

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#2650]
### What new functionality do you need?

The existing stage_ic job in forecast-only mode needs to be converted from shell to python. This should improve and enhance the job capabilities and make it more extensible.

This is a subtask of issue #2475.

### What are the requirements for the new functionality?

Existing job functionality should be retained but converted to python and yaml.

### Acceptance Criteria

Job still performs the same tasks.

### TODO

- [x] update `jobs/JGLOBAL_STAGE_IC` to use `.py` version of ex-script
- [x] rename `scripts/exglobal_stage_ic.sh` to `scripts/exglobal_stage_ic.py` and convert to python
- [x] create `ush/python/pygfs/task/stage.py` and populate with defs for staging
- [x] create `parm/stage` and create yaml files within for each stage mode
- [x] check `stage_ic` job setup and dependencies

**Comment by KateFriedman-NOAA** [comment]
Will take care of as part of PR for issue #2475. Closing as not needed.
