### ISSUE TITLE
Upgrade to BUFR 12.1.0

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow#2756]
### What new functionality do you need?

An upgrade to BUFR version 12.1.0 for the GSI and global workflow.  This version of BUFR has optimizations in it that allow the GSI to move to version 12.x without significant walltime increases.  Ideally, this will be included with spack-stack release 1.8.0.

Dependent issues:
- [x] https://github.com/JCSDA/spack-stack/issues/1060
- [x] https://github.com/NOAA-EMC/GSI/issues/642
- [x] https://github.com/NOAA-EMC/GSI-utils/issues/48
- [x] https://github.com/NOAA-EMC/gfs-utils/issues/29
- Possibly GDASApp.

### What are the requirements for the new functionality?

BUFR 12.1.0 would be used on all systems

### Acceptance Criteria

GSI jobs would run without a need for increased wall clock requests (or minimal increases).

### Suggest a solution (optional)

- [ ] Request a test installation on Hera and Orion.
- [ ] Run GSI ctests on both systems, comparing BUFR 11.7.0 and 12.1.0 for wall clock differences
- [ ] Run global-workflow test cases at various resolutions and adjust wall clocks if needed
- [ ] Once BUFR 12.1.0 is installed in official spack-stack releases on all machines (and on WCOSS2), run another round of tests and make final adjustments if necessary.
