### ISSUE TITLE
Upgrade to Spack-Stack 1.9.2

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [NOAA-EMC/global-workflow#2984]
### What new functionality do you need?

The global-workflow and subcomponents should all be upgraded to spack-stack 1.9.2.  Among other things, this upgrade will allow the workflow to use the same Python and BUFR libraries across all subcomponents.  There will still be a need for a "`gsi-addon`" environment (a misnomer as of 1.9.2) to enable the use of MET/METplus 9.1.3/3.1.1 in EMC_verif-global, but this environment will include all of the same modules as the `unified-dev` environment.  ~Also, an upstream requirement not yet in spack-stack 1.9.1 environments is CRTM v3.1.1, which will need to be incorporated into (at least) the GSI, UPP, UFS, and GDASApp.~

Upstream Issues/PRs

- [x] https://github.com/ufs-community/ufs-weather-model/issues/2345
- [x] https://github.com/ufs-community/ufs-weather-model/issues/2346
- [x] https://github.com/ufs-community/ufs-weather-model/issues/2541
- [x] https://github.com/ufs-community/ufs-weather-model/issues/2619
- [x] https://github.com/ufs-community/ufs-weather-model/pull/2650
- [x] https://github.com/NOAA-EMC/UPP/issues/1020 closed by https://github.com/NOAA-EMC/UPP/pull/1062
- [x] https://github.com/ufs-community/UFS_UTILS/issues/983
- [x] https://github.com/NOAA-EMC/GDASApp/issues/1283
- [x] https://github.com/NOAA-EMC/global-workflow/issues/2756
- [x] https://github.com/JCSDA/spack-stack/issues/1185
- [x] https://github.com/NOAA-EMC/WCOSS2-requests/issues/9
- [x] https://github.com/NOAA-EMC/WCOSS2-requests/issues/10

### What are the requirements for the new functionality?

- [ ] All supported platforms move to spack-stack 1.9.2
- [ ] All submodules update to spack-stack 1.9.2
- [ ] WCOSS2 module files should be updated for all submodules to match spack-stack 1.9.2 versions

### Acceptance Criteria

All builds and CI tests are successful on all tier-1 platforms:
- [ ] Hera
- [ ] WCOSS2
- [ ] Hercules
- [ ] Gaea C6

Ideally all builds and tests are successful on tier-2/3 platforms as well:
- [ ] Ursa
- [ ] Orion
- [ ] PW-AWS
- [ ] PW-Azure
- [ ] PW-GCP

**Comment by DavidHuber-NOAA** [comment]
It looks like things are moving along in the UFS, so I am un-blocking this.

**Comment by DavidHuber-NOAA** [comment]
The spack-stack developers expect version 1.9.0 to be more stable and robust than 1.8.0.  I have renamed this issue to reflect that we should move to 1.9.0 instead of 1.8.0 and will reapply the blocked label until the weather model upgrades to 1.9.0.

**Comment by DavidHuber-NOAA** [comment]
Noting here that applications built with spack-stack 1.9.1 appear to require significantly more memory as documented in https://github.com/JCSDA/spack-stack/issues/1588.  This will likely mean that resources will need to be reworked when moving to the new release.  The GDASApp port to Ursa (which uses 1.9.1) required additional memory for some tests.

**Comment by DavidHuber-NOAA** [comment]
Removing the `blocked` label.  Work can progress on this epic by upgrading all of the submodules except the UFS to 1.9.1 while that repository works out the kinks.

**Comment by DavidHuber-NOAA** [comment]
@RussTreadon-NOAA @EdwardSafford-NOAA @CoryMartin-NOAA @GeorgeGayno-NOAA @KateFriedman-NOAA

I would like to request that all of the submodules coordinate merging the spack-stack 1.9.1 pull requests.  Currently, the GSI is passing all regression tests on all platforms with 1.9.1 as is the UPP.  Pull requests are also open for GFS-Utils, GSI-Utils, and the GDASApp and one will be opened shortly for GSI-monitor.  The UPP pull request will be merged soon, which should be fine since it will require a merge into the UFS first.  For all other repositories, let's try to hold off on merging until they are all tested and ready to merge.

**Comment by RussTreadon-NOAA** [comment]
We are waiting for a [new CRTM tag](https://github.com/JCSDA/CRTMv3/issues/231#issuecomment-2944670185) (see CRTMv3 issue [#231](https://github.com/JCSDA/CRTMv3/issues/231) for details) to complete the GDASApp upgrade to spack-stack/1.9.1.

**Comment by RussTreadon-NOAA** [comment]
GDASApp updated to CRTM tag `v2.4.1-jedi.2` via GDASApp PR [#1750](https://github.com/NOAA-EMC/GDASApp/pull/1750).  This tag allows GDASApp to successfully run on Ursa using spack-stack/1.9.1.  GDASApp PR [#1750](https://github.com/NOAA-EMC/GDASApp/pull/1750) committed at [`f2e3a20`](https://github.com/NOAA-EMC/GDASApp/commit/f2e3a2089a77d65eb010b22d47b3fc048ab60f68) on 6/17/2025.

We should, however, update g-w `sorc/gdas.cd` to [`dbddc57`]( https://github.com/NOAA-EMC/GDASApp/commit/dbddc576a84dcb5f10d87e97bb3e090de52cec1a) (6/18/2025) or later since this hash includes updates to the Gaea build required by recent system maintenance.
