### ISSUE TITLE
GFSv16.3.26 - DA upgrade

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#2987]
### Description

Update to develop version of GSI to introduce bug fixes, optimization, and to simplify the future GFS v17 implementation.  Code changes to prepare for GOES-19, Metop-SG, Meteosat Third Generation and WSF-M.  Introduce GMI radiances, saildrones and Sentinal-6 GNSSRO.  Upgrade to CRTM 3.0 to simplify future support.

### Target version

v16.3.26

### Expected workflow changes

- [x] New GSI tag - [gfsda.v16.3.26](https://github.com/NOAA-EMC/GSI/releases/tag/gfsda.v16.3.26)
- [x] New scripts (pull GSI scripts into global-workflow)
- [x] New `crtm_ver=2.4.0.2`
- [x] New `ncdiag_ver=1.1.1`
- [x] Update `obsproc_run_ver=1.2.6` and `prepobs_run_ver=1.1.2`

### Tasks

- [x] Create release branch
- [x] Make workflow changes for upgrade in release branch (add additional checklist items as needed)
- [x] Create release notes
- [x] Cut hand-off tag for CDF
- [x] Submit CDF to NCO
- [ ] Implementation into operations complete
- [ ] Merge release branch into operational branch
- [ ] Cut version tag from operational branch
- [ ] Release new version tag
- [ ] Announce to users
- [ ] Update Read-The-Docs operations status version in develop

**Comment by KateFriedman-NOAA** [comment]
Related issue #3045 opened to document work for this issue.

**Comment by KateFriedman-NOAA** [comment]
GFSv16.4 tentative code handoff is 03/31/2025.

**Comment by ADCollard** [comment]
@KateFriedman-NOAA, A potentially dumb question.

I am getting failures in the `gfsmet*` jobs, apparently due to the upgrade from `verif_global_v2.10.0` to `verif_global_v2.10.4` in `GFSv16.3.22`.

The problem seems to be around line 191 of [ush/run_verif_global_in_global_workflow.sh](https://github.com/NOAA-EMC/EMC_verif-global/blob/ecb31f4575d86e9ce50495682adb550992ccfc6a/ush/run_verif_global_in_global_workflow.sh):

```
## Output set up
export jobid=${jobid:-${job}.${pid}}
export OUTPUTROOT=${DATA}
mkdir -p $DATA
cd $DATA
```

`$DATA` does not seem to be defined anywhere and was introduced in [this commit](https://github.com/NOAA-EMC/EMC_verif-global/commit/eb120ba9e907af4f99a465676b520046a6f8f82e).

Now for the dumb question: am I right in saying that this script is not used in operations and so this issue will not affect operational runs?  Was something special done in the pre-operational tests?

Thanks.

**Comment by KateFriedman-NOAA** [comment]
> am I right in saying that this script is not used in operations and so this issue will not affect operational runs?

Correct, the gfsmet* jobs are not run in operations. Thanks for letting me know of the issue. Can you point me to a log with the error? Thanks!

**Comment by ADCollard** [comment]
@KateFriedman-NOAA See /lfs/h2/emc/ptmp/andrew.collard/ROTDIRS/v16.4_hires/logs/2025032300/gfsmetpg2g1.log around line 908.

Is there a reason for upgrading `verif_global` or could we revert to `v2.10.0`?

**Comment by KateFriedman-NOAA** [comment]
@ADCollard The new v2.10.4 verif_global tag includes updates for renaming the Gulf of Mexico so we have to use it now, even if it's not in ops. There has also been another tag cut after that to add Gaea support.

Let's add a `DATA` setting into our `jobs/rocoto/metp.sh` since it will be more difficult to update the EMC_verif-global tag at this point. Replace [lines 51-52](https://github.com/NOAA-EMC/global-workflow/blob/release/gfs.v16.4/jobs/rocoto/metp.sh#L51-L52) in `jobs/rocoto/metp.sh` with:

```
export DATA=${DATAROOT}
mkdir -p "${DATA}"
```
Then retry the job and share the log once run. Thanks!

**Comment by ADCollard** [comment]
@KateFriedman-NOAA OK, I will try that.  Thanks.

**Comment by KateFriedman-NOAA** [comment]
Tag cut for hand-off: [EMC-v16.3.25](https://github.com/NOAA-EMC/global-workflow/releases/tag/EMC-v16.3.25)

**Comment by KateFriedman-NOAA** [comment]
This upgrade will now be v16.3.26, with v16.3.25 being the RTOFS v2.5 update only.

**Comment by ADCollard** [comment]
We need to ensure that some late local changes to GFSv16.3.26 are in this branch.

The following files differ between `release/gfs.v16.3.26` and `/lfs/h1/ops/prod/packages/gfs.v16.3.26`:

```
./docs/Release_Notes.md
./Externals.cfg
./.git/config
./.git/HEAD
./.git/index
./.git/logs/HEAD
./.git/logs/refs/remotes/origin/HEAD
./.git/packed-refs
./.gitignore
./scripts/exglobal_atmos_analysis.sh
./sorc/build_fv3.sh
./sorc/checkout.sh
./ush/ozn_xtrct.sh
./versions/hera.ver
./versions/orion.ver
./versions/wcoss2.ver
```

Of these the majority appears to have an older version of the file in the NCO directory.  I am not sure why this would be.   It does not appear to affect the results.

The following do need to be updated in `release/gfs.v16.3.26`:
`./scripts/exglobal_atmos_analysis.sh` - GMI temporarily turned off
`versions/*.ver` - obsproc and prepobs versions updated.
