### ISSUE TITLE
GFSv16.3.25 - Update wave grid post to check for indicator log file

### ISSUE THREAD

**Issue by MatthewMasarik-NOAA** [NOAA-EMC/global-workflow#3094]
### Description

The wave component should create a log file to indicate when a gridded output file has completed writing.  The global-workflow should be modified to check for this new logfile (Note: the current workflow implementation relies on loop timing within the wave post script).  The logfile name should be consistent with other components (ex, "log.${component}.f${fhr}").  To distinguish point vs. gridded output one suggestion is to use, "log.ww3.grd.f$fhr". 

Companion of #2987.

### Target version

v16.3.25

### Expected workflow changes

Updates to the wave gridded post-processing script, `exgfs_wave_post_gridded_sbs.sh`. 

### Tasks

- [x] Create release branch
- [x] Make workflow changes for upgrade in release branch (add additional checklist items as needed)
- [x] Create release notes
- [x] Cut hand-off tag for CDF
- [x] Submit CDF to NCO
- [ ] Implementation into operations complete
- [ ] Merge release branch into operational branch
- [ ] Cut version tag from operational branch
- [ ] Release new version tag
- [ ] Announce to users
- [ ] Update Read-The-Docs operations status version in develop

**Comment by MatthewMasarik-NOAA** [comment]
Fyi, @sbanihash @JessicaMeixner-NOAA

**Comment by sbanihash** [comment]
Thanks Matt!

Saeideh

**Comment by MatthewMasarik-NOAA** [comment]
**Related Issues**:
- ufs-community/ufs-weather-model:  https://github.com/ufs-community/ufs-weather-model/issues/2545
- NOAA-EMC/WW3: https://github.com/NOAA-EMC/WW3/issues/1321

**Comment by KateFriedman-NOAA** [comment]
GFSv16.4 tentative code handoff is 03/31/2025.

**Comment by MatthewMasarik-NOAA** [comment]
> GFSv16.4 tentative code handoff is 03/31/2025.

Thank you for the update, @KateFriedman-NOAA.  Testing is underway currently on my end.

**Comment by KateFriedman-NOAA** [comment]
Thanks for the PR @MatthewMasarik-NOAA ! This issue will close once v16.4 goes into ops and I merge the release branch into the `dev/gfs.v16` branch. I'll be handling that.

Will poke you and @JessicaMeixner-NOAA once v16.4 is in para ops testing so you can review the WW3 changes.

**Comment by MatthewMasarik-NOAA** [comment]
> Thanks for the PR [@MatthewMasarik-NOAA](https://github.com/MatthewMasarik-NOAA) ! This issue will close once v16.4 goes into ops and I merge the release branch into the `dev/gfs.v16` branch. I'll be handling that.
> 
> Will poke you and [@JessicaMeixner-NOAA](https://github.com/JessicaMeixner-NOAA) once v16.4 is in para ops testing so you can review the WW3 changes.

That sounds good, I'll keep an eye out to review the WW3 changes.

**Comment by KateFriedman-NOAA** [comment]
Tag cut for hand-off: [EMC-v16.3.25](https://github.com/NOAA-EMC/global-workflow/releases/tag/EMC-v16.3.25)

**Comment by JessicaMeixner-NOAA** [comment]
This is in ops. Closing
