### ISSUE TITLE
Switch to Meteosat-9 AMVs (WCOSS1 ops)

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#798]
**Description**

The GFS will upgrade in WCOSS1 operations to v16.1.8. This is an accelerated DA-only upgrade.

Meteosat-9 replaces Meteosat-8 as the operational geostationary platform over the Indian Ocean on 20220601.  To maintain continuity of operations, the /fix/fix_gsi/global_convinfo.txt file needs to be modified before this date (as soon as possible is preferable). @ADCollard @MichaelLueken-NOAA 

**Dependencies**

- [x] New GSI tag (`gfsda.v16.1.8`)

**To-do**

- [x] Create `release/gfs.v16.1.8` branch off `operations` branch.
- [x] Update GSI tag (`gfsda.v16.1.8`) in `release/gfs.v16.1.8`
- [x] Add release notes to `release/gfs.v16.1.8`
- [x] Cut hand-off tag from `release/gfs.v16.1.8`: `EMC-v16.1.8`
- [x] Hand-off `EMC-v16.1.8` to NCO (@ADCollard ?)
- [x] Merge `release/gfs.v16.1.8` into `operations` branch after implementation into WCOSS1 ops (via PR).
- [x] Cut `NCO-v16.1.8` tag from `operations` branch post-implementation PR merge and create release.
- [x] Merge v16.1.8 updates into `feature/ops-wcoss2` branch for GFSv.16.2.0 package
- [x] Implement v16.1.8 updates in to WCOSS2 v16.2.0 install.
- [x] Announce upgrade to glopara-announce listserv.

**Comment by KateFriedman-NOAA** [comment]
Created branch `release/gfs.v16.1.8` for this upgrade, cut from `operations` branch.

**Comment by MichaelLueken** [comment]
@KateFriedman-NOAA I have created the `gfsda.v16.1.8`, `gfsda.v16.2.0`, and `gfsda.v16.2.0.1` tags following the updates from @ADCollard.

Tag `gfsda.v16.1.8` was created at [6faf3e8](https://github.com/NOAA-EMC/GSI/commit/6faf3e8da2326d603a46587ef2e1c0956ac2d532).  

Tag `gfsda.v16.2.0` was created at [c54927a](https://github.com/NOAA-EMC/GSI/commit/c54927adf5e804fc5bf09c0b6d95a22476b47d6e).

Tag `gfsda.v16.2.0.1` was created at [cead592](https://github.com/NOAA-EMC/GSI/commit/cead59232fec46d4639c54c0afe0b02bfea211c0).

Please let me know if there are any issue you encounter.

**Comment by KateFriedman-NOAA** [comment]
Wonderful! Thanks for the quick updates @MichaelLueken-NOAA !

I will let NCO know they can proceed with the fresh install of v16.2.0 on WCOSS2 and then update the global-workflow `release/gfs.v16.1.8` branch with the new GSI tag.

**Comment by KateFriedman-NOAA** [comment]
@MichaelLueken-NOAA @ADCollard I have updated the `release/gfs.v16.18` branch with the new GSI tag `gfsda.v16.1.8` @ d24c1b2 and added the release notes provided by Andrew `Release_Notes.gfs.v16.1.8.txt` @ 7564aaf.

I will cut the `EMC-v16.1.8` tag for hand-off to NCO next.

**Comment by KateFriedman-NOAA** [comment]
@ADCollard Hand-off tag for NCO has been cut: [EMC-v16.1.8](https://github.com/NOAA-EMC/global-workflow/releases/tag/EMC-v16.1.8)

**Comment by KateFriedman-NOAA** [comment]
From May 27th RFC memo:
```
RFC 9515 - On WCOSS1, modify ‘global_convinfo.txt’ to turn on assimilation of
Meteosat-9 AMVs (Atmospheric Motion Vectors). Meteosat-9 replaces
Meteosat-8 as the operational geostationary platform over the Indian Ocean on
June 1. In order to maintain continuity of operations, the above file needs to be
modified. To be implemented on May 31 at 1140Z.
```

**Comment by KateFriedman-NOAA** [comment]
From SDM log (June 1st 5:50am):
```
6a. 1141Z - SPA Xiaoxue is starting work on RFC 9515 - Switch to Meteosat-9 AMVs in GFS. 1605Z - Complete.
```

**Comment by KateFriedman-NOAA** [comment]
@ADCollard Can you confirm that this update occurred in WCOSS1 and WCOSS2 ops? Thanks!

**Comment by KateFriedman-NOAA** [comment]
DA team confirmed the switch to Meteosat-9 occurred. From email thread shared with me by @RussTreadon-NOAA :

From @HaixiaLiu-NOAA :
```
Today is the 1st day that the Meteosat-9 becomes the primary satellite. I checked the operational gsistat for the 06 and 12z cycles. THe 06Z cycle assimilated M8 (SAID=55) data while the 12Z assimilated M9 (SAID=56) data. All look good and are as expected.

grep ' 0055 ' /gpfs/dell1/nco/ops/nwprod/../com/gfs/prod/gfs.20220601/06/atmos/gfs.t06z.gsistat  | grep 'o-g 01'
 o-g 01      uv asm 243 0055 count          0       1016       1921        966          0          0          0          0          0          0          0       3903
 o-g 01      uv asm 243 0055  bias  0.000E+00  0.344E+00  0.552E+00  0.912E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.587E+00
 o-g 01      uv asm 243 0055   rms  0.000E+00  0.199E+01  0.250E+01  0.342E+01  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.265E+01
 o-g 01      uv asm 243 0055  cpen  0.000E+00  0.860E-01  0.137E+00  0.254E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.152E+00
 o-g 01      uv asm 243 0055 qcpen  0.000E+00  0.857E-01  0.136E+00  0.252E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.152E+00
 o-g 01      uv asm 253 0055 count          0        583       1403          0          6        550        370        826        705         66          0       4509
 o-g 01      uv asm 253 0055  bias  0.000E+00  0.172E+00  0.434E+00  0.000E+00 -0.894E+00  0.300E+00 -0.871E-01  0.321E+00 -0.390E+00  0.927E+00  0.000E+00  0.197E+00
 o-g 01      uv asm 253 0055   rms  0.000E+00  0.154E+01  0.221E+01  0.000E+00  0.533E+01  0.462E+01  0.451E+01  0.417E+01  0.461E+01  0.611E+01  0.000E+00  0.363E+01
 o-g 01      uv asm 253 0055  cpen  0.000E+00  0.525E-01  0.108E+00  0.000E+00  0.253E+00  0.170E+00  0.141E+00  0.114E+00  0.139E+00  0.244E+00  0.000E+00  0.119E+00
 o-g 01      uv asm 253 0055 qcpen  0.000E+00  0.524E-01  0.108E+00  0.000E+00  0.253E+00  0.170E+00  0.140E+00  0.113E+00  0.139E+00  0.242E+00  0.000E+00  0.119E+00
 o-g 01      uv asm 254 0055 count          0          0          0          0          0       4576       3440       7111       6521        798          0      22446
 o-g 01      uv asm 254 0055  bias  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.726E+00  0.506E+00  0.564E+00  0.362E+00  0.120E+01  0.000E+00  0.552E+00
 o-g 01      uv asm 254 0055   rms  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.489E+01  0.488E+01  0.420E+01  0.464E+01  0.619E+01  0.000E+00  0.466E+01
 o-g 01      uv asm 254 0055  cpen  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.146E+00  0.143E+00  0.107E+00  0.130E+00  0.250E+00  0.000E+00  0.132E+00
 o-g 01      uv asm 254 0055 qcpen  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.145E+00  0.143E+00  0.107E+00  0.130E+00  0.248E+00  0.000E+00  0.132E+00

grep ' 0056 ' /gpfs/dell1/nco/ops/nwprod/../com/gfs/prod/gfs.20220601/12/atmos/gfs.t12z.gsistat  | grep 'o-g 01' (grep 0055 show nothing)
 o-g 01      uv asm 243 0056 count          0       1208       2334       1289          0          0          0          0          0          0          0       4831
 o-g 01      uv asm 243 0056  bias  0.000E+00 -0.164E+00  0.106E+00  0.356E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.105E+00
 o-g 01      uv asm 243 0056   rms  0.000E+00  0.192E+01  0.234E+01  0.301E+01  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.244E+01
 o-g 01      uv asm 243 0056  cpen  0.000E+00  0.814E-01  0.120E+00  0.198E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.131E+00
 o-g 01      uv asm 243 0056 qcpen  0.000E+00  0.813E-01  0.119E+00  0.197E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.131E+00
 o-g 01      uv asm 253 0056 count          0        729       1427          0          4        631        481        848        840        113          0       5073
 o-g 01      uv asm 253 0056  bias  0.000E+00 -0.125E+00  0.925E-01  0.000E+00 -0.112E+01  0.418E+00  0.319E+00  0.106E+00 -0.359E+00 -0.808E-01  0.000E+00  0.458E-01
 o-g 01      uv asm 253 0056   rms  0.000E+00  0.165E+01  0.214E+01  0.000E+00  0.532E+01  0.433E+01  0.436E+01  0.399E+01  0.452E+01  0.520E+01  0.000E+00  0.353E+01
 o-g 01      uv asm 253 0056  cpen  0.000E+00  0.604E-01  0.101E+00  0.000E+00  0.252E+00  0.148E+00  0.132E+00  0.104E+00  0.133E+00  0.176E+00  0.000E+00  0.112E+00
 o-g 01      uv asm 253 0056 qcpen  0.000E+00  0.603E-01  0.101E+00  0.000E+00  0.251E+00  0.147E+00  0.132E+00  0.103E+00  0.133E+00  0.176E+00  0.000E+00  0.111E+00
 o-g 01      uv asm 254 0056 count          0          0          0          0          0       5368       4869       8036       7384       1176          0      26833
 o-g 01      uv asm 254 0056  bias  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.614E+00  0.314E+00  0.509E+00  0.159E+00  0.708E+00  0.000E+00  0.407E+00
 o-g 01      uv asm 254 0056   rms  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.477E+01  0.455E+01  0.415E+01  0.444E+01  0.521E+01  0.000E+00  0.448E+01
 o-g 01      uv asm 254 0056  cpen  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.138E+00  0.125E+00  0.105E+00  0.120E+00  0.178E+00  0.000E+00  0.122E+00
 o-g 01      uv asm 254 0056 qcpen  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.000E+00  0.138E+00  0.124E+00  0.105E+00  0.119E+00  0.177E+00  0.000E+00  0.122E+00
```

@dtkleist also confirmed the same on WCOSS2. 

Upgrade is complete in both WCOSS1 and WCOSS2 operations. Will proceed with completing remaining global-workflow tasks for this implementation. Thanks all!

**Comment by KateFriedman-NOAA** [comment]
Sent announcement about WCOSS1 ops upgrade to glopara and FV3 listservs.

All tasks for GFSv16.1.8 upgrade are now complete. Closing issue. Thanks all!
