### ISSUE TITLE
Remove SDATE=CDATE IAU block in config.base.nco.static

### ISSUE THREAD

**Issue by KateFriedman-NOAA** [NOAA-EMC/global-workflow#960]
**Expected behavior**

The `IAU_OFFSET` value should be set to 6 (IAU on) and the `IAU_FHROT` value should be set to the first value in `IAUFHRS` variable (3).

**Current behavior**

`IAU_FHROT` is getting set to 0 and then filters down to the forecast job `fhrot` value. This is wrong. The forecast job fails.

**Machines affected**

All.

**Context**

@lgannoaa reported this issue while starting a warm-start parallel for GFSv16.3.0 testing on WCOSS2.

**To Reproduce**

Set up a warm-started run with wave restart files and use the NCO `config.base`.

**Detailed Description**

The NCO version of `config.base` (`config.base.nco.static`) contains a block that checks if CDATE=SDATE and if so, sets `IAU_OFFSET` and `IAU_FHROT` to 0. When using this config to start a warm-started run (atmos and wave) the wrong FHROT value is set and the forecast job fails. Since the `config.base.nco.static` config is only used in ops and it's always warm-start in ops, this block is not needed. Remove this block.

This isn't a problem in production since SDATE is very old but is an issue for pre-implementation testing.

**Possible Implementation**

Remove this block from `config.base.nco.static`:
```
if [[ "$SDATE" = "$CDATE" ]]; then
  export IAU_OFFSET=0
  export IAU_FHROT=0
fi
```

To do:

- [x] remove in `dev_v16.2.x` branch (#961)
- [x] remove in `release/gfs.v16.3.0` branch (#962)
- [x] remove in `develop` branch (#963)
